/**
 * SQL generation utilities.
 *
 * Pure functions for generating SQL that works across databases.
 */

export {
  buildInsightSQL,
  shortenAutoGeneratedName,
  getTableName,
  type BuildInsightSQLOptions,
} from "./insight-sql";
