/**
 * SQL generation utilities.
 *
 * Pure functions for generating SQL that works across databases.
 */

export {
  buildInsightSQL,
  shortenAutoGeneratedName,
  getTableName,
  metricToSqlExpression,
  type BuildInsightSQLOptions,
} from "./insight-sql";

export {
  resolveToSql,
  resolveForAnalysis,
  resolveEncodingToSql,
  type EncodingResolutionContext,
  type ResolvedForAnalysis,
  type ResolvedEncoding,
} from "./encoding-resolution";
