/**
 * SQL generation utilities.
 *
 * Pure functions for generating SQL that works across databases.
 */

export {
  buildInsightAvailableFields,
  buildInsightSQL,
  extractColumnAliasComponents,
  extractUUIDFromColumnAlias,
  // UUID column naming utilities
  fieldIdToColumnAlias,
  metricIdToColumnAlias,
  metricToSqlExpression,
  shortenAutoGeneratedName,
  type BuildInsightSQLOptions,
} from "./insight-sql";

export {
  resolveEncodingToResultFrame,
  resolveEncodingToSql,
  resolveForAnalysis,
  resolveToSql,
  type EncodingResolutionContext,
  type ResolvedEncoding,
  type ResolvedForAnalysis,
} from "./encoding-resolution";

export {
  applyDateTransformToSql,
  categoricalTransform,
  getAxisTypeForTransform,
  getDateTransformLabel,
  selectTemporalAggregation,
  temporalTransform,
} from "./date-transforms";

export {
  resolveEffectiveParams,
  type EffectiveParams,
} from "./override-resolution";

export { frameTableName } from "./frame-table-name";

export { quoteIdentifier, quoteLiteral } from "./quoting";

export {
  arrowDateToDuckDBDays,
  ARROW_ENCODING_BY_COLUMN_TYPE,
  DEFAULT_DUCKDB_INGEST_TYPE,
  duckdbJsonToEpochMillis,
  duckdbJsonToNumber,
  DUCKDB_INGEST_TYPE_BY_ARROW_TYPE,
  DUCKDB_TYPE_NAMES_BY_COLUMN_TYPE,
  FLECHETTE_DECODE_OPTIONS,
  MS_PER_DAY,
  type ArrowEncodingName,
  type IngestibleArrowTypeName,
} from "./type-translation";
