import next from "@next/eslint-plugin-next";
import reactHooks from "eslint-plugin-react-hooks";
import storybook from "eslint-plugin-storybook";
import { defineConfig } from "vite-plus";

const reactHooksRules = Object.fromEntries(
  Object.entries(reactHooks.configs.flat.recommended.rules).map(
    ([name, severity]) => [
      name.replace("react-hooks/", "react-hooks-js/"),
      severity,
    ],
  ),
);
const nextRules = {
  ...next.configs.recommended.rules,
  ...next.configs["core-web-vitals"].rules,
};
const storybookRules = Object.assign(
  {},
  ...storybook.configs["flat/recommended"].map((config) => config.rules ?? {}),
);

export default defineConfig({
  lint: {
    plugins: ["oxc", "typescript", "react"],
    jsPlugins: [
      "eslint-plugin-sonarjs",
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
      {
        name: "dashframe",
        specifier: "./scripts/oxlint-plugin-dashframe.mjs",
      },
      {
        name: "anti-slop",
        specifier: "./scripts/oxlint-plugin-anti-slop/index.ts",
      },
      {
        name: "@next/next",
        specifier: "@next/eslint-plugin-next",
      },
      {
        name: "storybook",
        specifier: "eslint-plugin-storybook",
      },
      {
        name: "react-hooks-js",
        specifier: "eslint-plugin-react-hooks",
      },
    ],
    categories: {
      correctness: "off",
    },
    env: {
      builtin: true,
    },
    settings: {
      react: {
        version: "999.999.999",
      },
    },
    ignorePatterns: [
      "node_modules/**",
      "**/.next/**",
      "**/dist/**",
      "**/build/**",
      "**/out/**",
      "apps/web/next-env.d.ts",
      "apps/web/.next-e2e/**",
      "apps/renderer/src/routeTree.gen.ts",
      "apps/web/src/routeTree.gen.ts",
      "libs/**",
    ],
    rules: {
      "no-array-constructor": "error",
      "no-unused-expressions": "error",
      "no-unused-vars": "off",
      "sonarjs/class-name": "error",
      "sonarjs/no-commented-code": "error",
      "sonarjs/no-fallthrough": "error",
      "sonarjs/no-equals-in-for-termination": "error",
      "sonarjs/no-extra-arguments": "error",
      "sonarjs/no-labels": "error",
      "sonarjs/no-nested-assignment": "error",
      "sonarjs/no-redundant-boolean": "error",
      "sonarjs/prefer-single-boolean-return": "error",
      "sonarjs/unused-import": "error",
      "sonarjs/no-case-label-in-switch": "error",
      "sonarjs/no-parameter-reassignment": "error",
      "sonarjs/prefer-while": "error",
      "sonarjs/no-small-switch": "error",
      "sonarjs/no-hardcoded-ip": "error",
      "sonarjs/label-position": "error",
      "sonarjs/public-static-readonly": "error",
      "sonarjs/call-argument-line": "error",
      "sonarjs/max-switch-cases": "error",
      "sonarjs/no-unused-vars": "off",
      "sonarjs/function-inside-loop": "error",
      "sonarjs/code-eval": "error",
      "sonarjs/future-reserved-words": "error",
      "sonarjs/bitwise-operators": "error",
      "sonarjs/no-primitive-wrappers": "error",
      "sonarjs/no-skipped-tests": "error",
      "sonarjs/no-identical-expressions": "error",
      "sonarjs/constructor-for-side-effects": "error",
      "sonarjs/no-dead-store": "error",
      "sonarjs/no-identical-conditions": "error",
      "sonarjs/no-duplicated-branches": "error",
      "sonarjs/deprecation": "error",
      "sonarjs/no-inverted-boolean-check": "error",
      "sonarjs/misplaced-loop-counter": "error",
      "sonarjs/no-nested-functions": "error",
      "sonarjs/no-hardcoded-passwords": "error",
      "sonarjs/sql-queries": "error",
      "sonarjs/insecure-cookie": "error",
      "sonarjs/no-useless-increment": "error",
      "sonarjs/no-globals-shadowing": "error",
      "sonarjs/no-empty-test-file": "error",
      "sonarjs/no-ignored-return": "error",
      "sonarjs/arguments-order": "error",
      "sonarjs/pseudo-random": "error",
      "sonarjs/for-loop-increment-sign": "error",
      "sonarjs/null-dereference": "error",
      "sonarjs/no-selector-parameter": "error",
      "sonarjs/updated-loop-counter": "error",
      "sonarjs/block-scoped-var": "error",
      "sonarjs/no-ignored-exceptions": "error",
      "sonarjs/no-gratuitous-expressions": "error",
      "sonarjs/file-uploads": "error",
      "sonarjs/file-permissions": "error",
      "sonarjs/no-empty-character-class": "error",
      "sonarjs/no-unenclosed-multiline-block": "error",
      "sonarjs/index-of-compare-to-positive-number": "error",
      "sonarjs/assertions-in-tests": "error",
      "sonarjs/no-implicit-global": "error",
      "sonarjs/no-useless-catch": "error",
      "sonarjs/xml-parser-xxe": "error",
      "sonarjs/non-existent-operator": "error",
      "sonarjs/post-message": "error",
      "sonarjs/no-array-delete": "error",
      "sonarjs/no-alphabetical-sort": "error",
      "sonarjs/no-incomplete-assertions": "error",
      "sonarjs/no-global-this": "error",
      "sonarjs/new-operator-misuse": "error",
      "sonarjs/no-delete-var": "error",
      "sonarjs/cookie-no-httponly": "error",
      "sonarjs/no-nested-conditional": "error",
      "sonarjs/different-types-comparison": "error",
      "sonarjs/inverted-assertion-arguments": "error",
      "sonarjs/updated-const-var": "error",
      "sonarjs/no-invariant-returns": "error",
      "sonarjs/generator-without-yield": "error",
      "sonarjs/no-associative-arrays": "error",
      "sonarjs/comma-or-logical-or-case": "error",
      "sonarjs/no-redundant-jump": "error",
      "sonarjs/inconsistent-function-call": "error",
      "sonarjs/no-use-of-empty-return-value": "error",
      "sonarjs/void-use": "error",
      "sonarjs/cognitive-complexity": "error",
      "sonarjs/argument-type": "error",
      "sonarjs/in-operator-type-error": "error",
      "sonarjs/array-callback-without-return": "error",
      "sonarjs/function-return-type": "error",
      "sonarjs/super-invocation": "error",
      "sonarjs/no-all-duplicated-branches": "error",
      "sonarjs/no-same-line-conditional": "error",
      "sonarjs/no-collection-size-mischeck": "error",
      "sonarjs/no-unthrown-error": "error",
      "sonarjs/no-unused-collection": "error",
      "sonarjs/no-os-command-from-path": "error",
      "sonarjs/no-misleading-array-reverse": "error",
      "sonarjs/no-element-overwrite": "error",
      "sonarjs/no-identical-functions": "error",
      "sonarjs/no-empty-collection": "error",
      "sonarjs/no-redundant-assignments": "error",
      "sonarjs/prefer-type-guard": "error",
      "sonarjs/use-type-alias": "error",
      "sonarjs/no-useless-intersection": "error",
      "sonarjs/weak-ssl": "error",
      "sonarjs/no-weak-keys": "error",
      "sonarjs/csrf": "error",
      "sonarjs/production-debug": "error",
      "sonarjs/prefer-default-last": "error",
      "sonarjs/no-in-misuse": "error",
      "sonarjs/no-duplicate-in-composite": "error",
      "sonarjs/no-undefined-argument": "error",
      "sonarjs/no-nested-template-literals": "error",
      "sonarjs/prefer-promise-shorthand": "error",
      "sonarjs/os-command": "error",
      "sonarjs/no-redundant-optional": "error",
      "sonarjs/hashing": "error",
      "sonarjs/no-try-promise": "error",
      "sonarjs/unverified-certificate": "error",
      "sonarjs/no-unsafe-unzip": "error",
      "sonarjs/cors": "error",
      "sonarjs/link-with-target-blank": "error",
      "sonarjs/disabled-auto-escaping": "error",
      "sonarjs/table-header": "error",
      "sonarjs/no-table-as-layout": "error",
      "sonarjs/table-header-reference": "error",
      "sonarjs/object-alt-content": "error",
      "sonarjs/no-clear-text-protocols": "error",
      "sonarjs/publicly-writable-directories": "error",
      "sonarjs/unverified-hostname": "error",
      "sonarjs/encryption-secure-mode": "error",
      "sonarjs/no-weak-cipher": "error",
      "sonarjs/no-intrusive-permissions": "error",
      "sonarjs/insecure-jwt-token": "error",
      "sonarjs/x-powered-by": "error",
      "sonarjs/hidden-files": "error",
      "sonarjs/content-length": "error",
      "sonarjs/disabled-resource-integrity": "error",
      "sonarjs/content-security-policy": "error",
      "sonarjs/no-mixed-content": "error",
      "sonarjs/frame-ancestors": "error",
      "sonarjs/no-mime-sniff": "error",
      "sonarjs/no-referrer-policy": "error",
      "sonarjs/strict-transport-security": "error",
      "sonarjs/confidential-information-logging": "error",
      "sonarjs/no-ip-forward": "error",
      "sonarjs/empty-string-repetition": "error",
      "sonarjs/regex-complexity": "error",
      "sonarjs/anchor-precedence": "error",
      "sonarjs/slow-regex": "error",
      "sonarjs/no-invalid-regexp": "error",
      "sonarjs/unused-named-groups": "error",
      "sonarjs/no-same-argument-assert": "error",
      "sonarjs/no-misleading-character-class": "error",
      "sonarjs/duplicates-in-character-class": "error",
      "sonarjs/session-regeneration": "error",
      "sonarjs/test-check-exception": "error",
      "sonarjs/stable-tests": "error",
      "sonarjs/no-empty-after-reluctant": "error",
      "sonarjs/single-character-alternation": "error",
      "sonarjs/no-code-after-done": "error",
      "sonarjs/disabled-timeout": "error",
      "sonarjs/chai-determinate-assertion": "error",
      "sonarjs/aws-s3-bucket-insecure-http": "error",
      "sonarjs/aws-s3-bucket-versioning": "error",
      "sonarjs/aws-s3-bucket-granted-access": "error",
      "sonarjs/no-angular-bypass-sanitization": "error",
      "sonarjs/aws-iam-public-access": "error",
      "sonarjs/aws-ec2-unencrypted-ebs-volume": "error",
      "sonarjs/aws-s3-bucket-public-access": "error",
      "sonarjs/aws-iam-all-privileges": "error",
      "sonarjs/aws-rds-unencrypted-databases": "error",
      "sonarjs/aws-opensearchservice-domain": "error",
      "sonarjs/aws-iam-privilege-escalation": "error",
      "sonarjs/aws-sagemaker-unencrypted-notebook": "error",
      "sonarjs/aws-restricted-ip-admin-access": "error",
      "sonarjs/no-empty-alternatives": "error",
      "sonarjs/no-control-regex": "error",
      "sonarjs/no-regex-spaces": "error",
      "sonarjs/aws-sns-unencrypted-topics": "error",
      "sonarjs/existing-groups": "error",
      "sonarjs/aws-ec2-rds-dms-public": "error",
      "sonarjs/aws-sqs-unencrypted-queue": "error",
      "sonarjs/no-empty-group": "error",
      "sonarjs/aws-efs-unencrypted": "error",
      "sonarjs/aws-apigateway-public-api": "error",
      "sonarjs/stateful-regex": "error",
      "sonarjs/concise-regex": "error",
      "sonarjs/single-char-in-character-classes": "error",
      "sonarjs/no-hardcoded-secrets": "error",
      "sonarjs/no-exclusive-tests": "error",
      "sonarjs/hardcoded-secret-signatures": "error",
      "sonarjs/jsx-no-leaked-render": "error",
      "sonarjs/no-hook-setter-in-body": "error",
      "sonarjs/no-useless-react-setstate": "error",
      "sonarjs/no-uniq-key": "error",
      "sonarjs/redundant-type-aliases": "error",
      "sonarjs/prefer-regexp-exec": "error",
      "sonarjs/no-internal-api-use": "error",
      "sonarjs/prefer-read-only-props": "error",
      "sonarjs/no-literal-call": "error",
      "sonarjs/reduce-initial-value": "error",
      "sonarjs/no-async-constructor": "error",
      "sonarjs/review-blockchain-mnemonic": "error",
      "sonarjs/dynamically-constructed-templates": "error",
      "typescript/no-unused-vars": [
        "warn",
        {
          ignoreRestSiblings: true,
          varsIgnorePattern: "^_",
          argsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "dashframe/credential-class-literals": "error",
      "anti-slop/no-reflect-apply": "error",
      "anti-slop/no-widen-then-assert": "error",
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@wystack/server",
              message:
                "@wystack/server's raw command types (e.g. Command) are server-internal. Build commands via cmd()/CommandPayloads in apps/server/src/functions/commands.ts, or call the server's RPC surface — don't hand-assemble a { path, args } literal.",
            },
          ],
          patterns: [
            {
              group: [
                "**/functions/commands",
                "**/functions/commands.js",
                "**/functions/commands.ts",
              ],
              message:
                "apps/server/src/functions/commands.ts is the command builder layer — importable only from within apps/server. Use the server's RPC/command API instead of reaching into it directly.",
            },
          ],
        },
      ],
      "typescript/ban-ts-comment": "error",
      "typescript/no-duplicate-enum-values": "error",
      "typescript/no-empty-object-type": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-extra-non-null-assertion": "error",
      "typescript/no-misused-new": "error",
      "typescript/no-namespace": "error",
      "typescript/no-non-null-asserted-optional-chain": "error",
      "typescript/no-require-imports": "error",
      "typescript/no-this-alias": "error",
      "typescript/no-unnecessary-type-constraint": "error",
      "typescript/no-unsafe-declaration-merging": "error",
      "typescript/no-unsafe-function-type": "error",
      "typescript/no-wrapper-object-types": "error",
      "typescript/prefer-as-const": "error",
      "typescript/prefer-namespace-keyword": "error",
      "typescript/triple-slash-reference": "error",
      "vite-plus/prefer-vite-plus-imports": "error",
    },
    overrides: [
      {
        files: ["packages/app/**/*.ts", "packages/app/**/*.tsx"],
        rules: reactHooksRules,
      },
      {
        files: ["apps/web/**/*.ts", "apps/web/**/*.tsx"],
        plugins: ["nextjs", "jsx-a11y"],
        rules: {
          ...reactHooksRules,
          ...nextRules,
        },
      },
      {
        files: [
          "packages/ui/**/*.stories.ts",
          "packages/ui/**/*.stories.tsx",
          "packages/ui/.storybook/**/*.ts",
          "packages/ui/.storybook/**/*.tsx",
        ],
        rules: storybookRules,
      },
      {
        files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
        rules: {
          "constructor-super": "off",
          "getter-return": "off",
          "no-class-assign": "off",
          "no-const-assign": "off",
          "no-dupe-class-members": "off",
          "no-dupe-keys": "off",
          "no-func-assign": "off",
          "no-import-assign": "off",
          "no-new-native-nonconstructor": "off",
          "no-obj-calls": "off",
          "no-redeclare": "off",
          "no-setter-return": "off",
          "no-this-before-super": "off",
          "no-undef": "off",
          "no-unreachable": "off",
          "no-unsafe-negation": "off",
          "no-var": "error",
          "no-with": "off",
          "prefer-const": "error",
          "prefer-rest-params": "error",
          "prefer-spread": "error",
        },
      },
      {
        files: [
          "**/*.test.ts",
          "**/*.test.tsx",
          "**/*.spec.ts",
          "**/*.spec.tsx",
        ],
        rules: {
          "sonarjs/no-nested-functions": "off",
          "dashframe/credential-class-literals": "off",
        },
        jsPlugins: ["eslint-plugin-sonarjs"],
      },
      {
        files: ["**/credential-classes.ts"],
        rules: {
          "dashframe/credential-class-literals": "off",
        },
      },
      {
        files: ["scripts/oxlint-plugin-dashframe.mjs"],
        rules: {
          "dashframe/credential-class-literals": "off",
        },
      },
      {
        files: ["vite.config.ts"],
        rules: {
          "sonarjs/no-hardcoded-passwords": "off",
        },
      },
      {
        files: ["apps/server/**/*.ts", "apps/server/**/*.tsx"],
        rules: {
          "no-restricted-imports": [
            "error",
            {
              paths: [],
              patterns: [],
            },
          ],
        },
      },
    ],
    options: {
      typeAware: false,
      typeCheck: false,
    },
  },
  fmt: {
    printWidth: 80,
    sortPackageJson: false,
    ignorePatterns: [
      "node_modules",
      "**/dist",
      "**/build",
      "**/.next",
      "**/.next-e2e",
      "**/out",
      "**/.turbo",
      "coverage",
      "pnpm-lock.yaml",
      "*.tsbuildinfo",
      "**/*.tsbuildinfo",
      "e2e/web/features/.generated",
      "e2e/web/test-results",
      "apps/renderer/src/routeTree.gen.ts",
      "apps/web/src/routeTree.gen.ts",
      "libs/",
    ],
  },
});
