/**
 * @dashframe/engine
 *
 * Abstract engine interfaces for DashFrame computation.
 * This package defines contracts that can be implemented for different runtimes:
 * - @dashframe/engine-browser: DuckDB-WASM + IndexedDB (browser)
 * - @dashframe/engine-server: DuckDB native + PostgreSQL (server)
 * - @dashframe/engine-mobile: SQLite (mobile)
 *
 * Re-exports @dashframe/core for convenience.
 */

// Re-export all types
export * from "@dashframe/types";

// ============================================================================
// Engine Interfaces
// ============================================================================

export type {
  DataFrame,
  DataFrameFactory,
  DataFrameJSON,
  // Storage
  DataFrameStorage,
  // DataFrame
  DataFrameStorageLocation,
  ExecutionPlan,
  ExecutionReason,
  ExecutionStrategy,
  PushDownOperation,
  // Query Planner
  Query,
  QueryAggregation,
  QueryEngine,
  QueryFilter,
  QueryPlanner,
  QueryPushDownCapable,
  // Query Engine
  QueryResult,
  QuerySort,
} from "./interfaces";

export { isQueryPushDownCapable } from "./interfaces";

// ============================================================================
// Connector Pattern
// ============================================================================

export {
  BaseConnector,
  FileSourceConnector,
  RemoteApiConnector,
  isFileConnector,
  isRemoteApiConnector,
} from "./connector";

export type {
  AnyConnector,
  ConnectorQueryResult,
  FileParseResult,
  FormField,
  FormFieldType,
  QueryOptions,
  RemoteDatabase,
  SourceType,
  ValidationResult,
} from "./connector";

// ============================================================================
// Query Types
// ============================================================================

export type {
  Aggregation,
  AggregationFunction,
  FilterOperator,
  FilterPredicate,
  JoinOptions,
  JoinType,
  SortDirection,
  SortOrder,
} from "./types";

// ============================================================================
// SQL Generation
// ============================================================================

export {
  buildInsightSQL,
  extractUUIDFromColumnAlias,
  // UUID column naming utilities
  fieldIdToColumnAlias,
  getTableName,
  metricIdToColumnAlias,
  metricToSqlExpression,
  shortenAutoGeneratedName,
  type BuildInsightSQLOptions,
} from "./sql";

// ============================================================================
// Encoding Resolution
// ============================================================================

export {
  resolveEncodingToSql,
  resolveForAnalysis,
  resolveToSql,
  type EncodingResolutionContext,
  type ResolvedEncoding,
  type ResolvedForAnalysis,
} from "./sql";

// ============================================================================
// Date Transforms
// ============================================================================

export {
  applyDateTransformToSql,
  categoricalTransform,
  getAxisTypeForTransform,
  getDateTransformLabel,
  selectTemporalAggregation,
  temporalTransform,
} from "./sql";
