/**
 * @dashframe/engine
 *
 * Abstract engine interfaces for DashFrame computation.
 * This package defines contracts that can be implemented for different runtimes:
 * - @dashframe/engine-browser: DuckDB-WASM helpers + IndexedDB (browser)
 * - @dashframe/engine-server: NativeDuckDBEngine (server)
 *
 * Re-exports @dashframe/types for convenience.
 */

// Re-export all types
export * from "@dashframe/types";

// ============================================================================
// Engine Interfaces
// ============================================================================

export type {
  DataFrame,
  DataFrameFactory,
  DataFrameJSON,
  // Storage
  DataFrameStorage,
  // DataFrame
  DataFrameStorageLocation,
  // Query Engine
  QueryEngine,
  QueryResult,
} from "./interfaces";

export {
  defineColumnTypeMap,
  inferPrimitiveColumnType,
  type ColumnTypeMap,
} from "./column-type-map";

// ============================================================================
// Connector Pattern
// ============================================================================

export {
  BaseConnector,
  FileSourceConnector,
  RemoteApiConnector,
  createFieldsFromColumns,
  createSourceSchema,
  detectPrimaryKeyColumn,
  inferStringColumnType,
  isFileConnector,
  isRemoteApiConnector,
  parsePrimitiveBoolean,
  parsePrimitiveValueByType,
  parseStringValueByType,
} from "./connector";

export type {
  AnyConnector,
  ConnectorColumn,
  ConnectorQueryResult,
  FileParseResult,
  FormField,
  FormFieldType,
  QueryOptions,
  RemoteDatabase,
  SecretResolver,
  SourceType,
  SystemFieldInput,
  ValidationResult,
} from "./connector";

// ============================================================================
// Query Types
// ============================================================================

export type {
  Aggregation,
  AggregationFunction,
  FilterOperator,
  FilterPredicate,
  JoinOptions,
  JoinType,
  SortDirection,
  SortOrder,
} from "./types";

// ============================================================================
// SQL Generation
// ============================================================================

export {
  buildInsightAvailableFields,
  buildInsightSQL,
  extractColumnAliasComponents,
  extractUUIDFromColumnAlias,
  // UUID column naming utilities
  fieldIdToColumnAlias,
  getTableName,
  metricIdToColumnAlias,
  metricToSqlExpression,
  shortenAutoGeneratedName,
  type BuildInsightSQLOptions,
} from "./sql";

// ============================================================================
// Encoding Resolution
// ============================================================================

export {
  resolveEncodingToSql,
  resolveForAnalysis,
  resolveToSql,
  type EncodingResolutionContext,
  type ResolvedEncoding,
  type ResolvedForAnalysis,
} from "./sql";

// ============================================================================
// Date Transforms
// ============================================================================

export {
  applyDateTransformToSql,
  categoricalTransform,
  getAxisTypeForTransform,
  getDateTransformLabel,
  selectTemporalAggregation,
  temporalTransform,
} from "./sql";

// ============================================================================
// Override Resolution (dashboard per-cell compile-time coalesce)
// ============================================================================

export { resolveEffectiveParams, type EffectiveParams } from "./sql";

// ============================================================================
// SQL Quoting Utilities
// ============================================================================

export { quoteIdentifier, quoteLiteral } from "./sql";

// ============================================================================
// Visualization Labels
// ============================================================================

export {
  formatAggregationLabel,
  getMetricDisplayLabel,
  isGeneratedColumnLabel,
} from "./visualization-labels";
