/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../../packages/app/src/routes/__root'
import { Route as DataFramesRouteImport } from './../../../packages/app/src/routes/data-frames'
import { Route as IndexRouteImport } from './../../../packages/app/src/routes/index'
import { Route as VisualizationsIndexRouteImport } from './../../../packages/app/src/routes/visualizations/index'
import { Route as InsightsIndexRouteImport } from './../../../packages/app/src/routes/insights/index'
import { Route as DataSourcesIndexRouteImport } from './../../../packages/app/src/routes/data-sources/index'
import { Route as DashboardsIndexRouteImport } from './../../../packages/app/src/routes/dashboards/index'
import { Route as VisualizationsVisualizationIdRouteImport } from './../../../packages/app/src/routes/visualizations/$visualizationId'
import { Route as InsightsInsightIdRouteImport } from './../../../packages/app/src/routes/insights/$insightId'
import { Route as DataSourcesSourceIdRouteImport } from './../../../packages/app/src/routes/data-sources/$sourceId'
import { Route as DashboardsDashboardIdRouteImport } from './../../../packages/app/src/routes/dashboards/$dashboardId'
import { Route as InsightsInsightIdJoinTableIdRouteImport } from './../../../packages/app/src/routes/insights/$insightId_.join.$tableId'

const DataFramesRoute = DataFramesRouteImport.update({
  id: '/data-frames',
  path: '/data-frames',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizationsIndexRoute = VisualizationsIndexRouteImport.update({
  id: '/visualizations/',
  path: '/visualizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesIndexRoute = DataSourcesIndexRouteImport.update({
  id: '/data-sources/',
  path: '/data-sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizationsVisualizationIdRoute =
  VisualizationsVisualizationIdRouteImport.update({
    id: '/visualizations/$visualizationId',
    path: '/visualizations/$visualizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsInsightIdRoute = InsightsInsightIdRouteImport.update({
  id: '/insights/$insightId',
  path: '/insights/$insightId',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesSourceIdRoute = DataSourcesSourceIdRouteImport.update({
  id: '/data-sources/$sourceId',
  path: '/data-sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsDashboardIdRoute = DashboardsDashboardIdRouteImport.update({
  id: '/dashboards/$dashboardId',
  path: '/dashboards/$dashboardId',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsInsightIdJoinTableIdRoute =
  InsightsInsightIdJoinTableIdRouteImport.update({
    id: '/insights/$insightId_/join/$tableId',
    path: '/insights/$insightId/join/$tableId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-frames': typeof DataFramesRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/data-sources/$sourceId': typeof DataSourcesSourceIdRoute
  '/insights/$insightId': typeof InsightsInsightIdRoute
  '/visualizations/$visualizationId': typeof VisualizationsVisualizationIdRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/data-sources/': typeof DataSourcesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/visualizations/': typeof VisualizationsIndexRoute
  '/insights/$insightId/join/$tableId': typeof InsightsInsightIdJoinTableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-frames': typeof DataFramesRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/data-sources/$sourceId': typeof DataSourcesSourceIdRoute
  '/insights/$insightId': typeof InsightsInsightIdRoute
  '/visualizations/$visualizationId': typeof VisualizationsVisualizationIdRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/data-sources': typeof DataSourcesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/visualizations': typeof VisualizationsIndexRoute
  '/insights/$insightId/join/$tableId': typeof InsightsInsightIdJoinTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-frames': typeof DataFramesRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/data-sources/$sourceId': typeof DataSourcesSourceIdRoute
  '/insights/$insightId': typeof InsightsInsightIdRoute
  '/visualizations/$visualizationId': typeof VisualizationsVisualizationIdRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/data-sources/': typeof DataSourcesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/visualizations/': typeof VisualizationsIndexRoute
  '/insights/$insightId_/join/$tableId': typeof InsightsInsightIdJoinTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-frames'
    | '/dashboards/$dashboardId'
    | '/data-sources/$sourceId'
    | '/insights/$insightId'
    | '/visualizations/$visualizationId'
    | '/dashboards/'
    | '/data-sources/'
    | '/insights/'
    | '/visualizations/'
    | '/insights/$insightId/join/$tableId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-frames'
    | '/dashboards/$dashboardId'
    | '/data-sources/$sourceId'
    | '/insights/$insightId'
    | '/visualizations/$visualizationId'
    | '/dashboards'
    | '/data-sources'
    | '/insights'
    | '/visualizations'
    | '/insights/$insightId/join/$tableId'
  id:
    | '__root__'
    | '/'
    | '/data-frames'
    | '/dashboards/$dashboardId'
    | '/data-sources/$sourceId'
    | '/insights/$insightId'
    | '/visualizations/$visualizationId'
    | '/dashboards/'
    | '/data-sources/'
    | '/insights/'
    | '/visualizations/'
    | '/insights/$insightId_/join/$tableId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataFramesRoute: typeof DataFramesRoute
  DashboardsDashboardIdRoute: typeof DashboardsDashboardIdRoute
  DataSourcesSourceIdRoute: typeof DataSourcesSourceIdRoute
  InsightsInsightIdRoute: typeof InsightsInsightIdRoute
  VisualizationsVisualizationIdRoute: typeof VisualizationsVisualizationIdRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
  DataSourcesIndexRoute: typeof DataSourcesIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  VisualizationsIndexRoute: typeof VisualizationsIndexRoute
  InsightsInsightIdJoinTableIdRoute: typeof InsightsInsightIdJoinTableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/data-frames': {
      id: '/data-frames'
      path: '/data-frames'
      fullPath: '/data-frames'
      preLoaderRoute: typeof DataFramesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizations/': {
      id: '/visualizations/'
      path: '/visualizations'
      fullPath: '/visualizations/'
      preLoaderRoute: typeof VisualizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources/': {
      id: '/data-sources/'
      path: '/data-sources'
      fullPath: '/data-sources/'
      preLoaderRoute: typeof DataSourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizations/$visualizationId': {
      id: '/visualizations/$visualizationId'
      path: '/visualizations/$visualizationId'
      fullPath: '/visualizations/$visualizationId'
      preLoaderRoute: typeof VisualizationsVisualizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$insightId': {
      id: '/insights/$insightId'
      path: '/insights/$insightId'
      fullPath: '/insights/$insightId'
      preLoaderRoute: typeof InsightsInsightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources/$sourceId': {
      id: '/data-sources/$sourceId'
      path: '/data-sources/$sourceId'
      fullPath: '/data-sources/$sourceId'
      preLoaderRoute: typeof DataSourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId': {
      id: '/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof DashboardsDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$insightId_/join/$tableId': {
      id: '/insights/$insightId_/join/$tableId'
      path: '/insights/$insightId/join/$tableId'
      fullPath: '/insights/$insightId/join/$tableId'
      preLoaderRoute: typeof InsightsInsightIdJoinTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataFramesRoute: DataFramesRoute,
  DashboardsDashboardIdRoute: DashboardsDashboardIdRoute,
  DataSourcesSourceIdRoute: DataSourcesSourceIdRoute,
  InsightsInsightIdRoute: InsightsInsightIdRoute,
  VisualizationsVisualizationIdRoute: VisualizationsVisualizationIdRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
  DataSourcesIndexRoute: DataSourcesIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  VisualizationsIndexRoute: VisualizationsIndexRoute,
  InsightsInsightIdJoinTableIdRoute: InsightsInsightIdJoinTableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
