import type { DataTable, InsightJoinConfig } from "@dashframe/types";
import { describe, expect, it } from "vitest";
import {
  computeCombinedFields,
  computeFilterableFields,
  type CombinedField,
} from "./compute-combined-fields";

/**
 * Locks the filterable-field narrowing used by the FilterEditDialog picker.
 * Every offered field must back a working, unambiguous predicate — so dropped
 * right join-keys and ambiguous duplicate column names are excluded. Mirrors
 * the insight SQL builder's join emission (right join-key dropped) and its
 * column-name-based filter resolution.
 */

function makeTable(id: string, name: string, fieldNames: string[]): DataTable {
  return {
    id,
    name,
    fields: fieldNames.map((n) => ({
      id: `${id}-${n}`,
      name: n,
      type: "string" as const,
    })),
  } as unknown as DataTable;
}

describe("computeCombinedFields", () => {
  it("disambiguates a 2-way joined-vs-joined column collision (base lacks the name)", () => {
    // Regression: old code only checked base-vs-joined collisions. If two
    // joined tables share a column name absent from the base, both fields
    // stayed unprefixed → duplicate displayNames in the combined output.
    const base = makeTable("t-base", "users", ["name"]);
    const joinA = makeTable("t-a", "accounts", ["id", "email"]);
    const joinB = makeTable("t-b", "bookings", ["id", "date"]);

    const joins: InsightJoinConfig[] = [
      {
        type: "inner",
        rightTableId: "t-a",
        leftKey: "account_id",
        rightKey: "id",
      },
      {
        type: "inner",
        rightTableId: "t-b",
        leftKey: "booking_id",
        rightKey: "id",
      },
    ];

    const { fields } = computeCombinedFields(base, joins, [base, joinA, joinB]);
    const displayNames = fields.map((f) => f.displayName);

    // All display names must be unique — no two fields may share one.
    const unique = new Set(displayNames);
    expect(unique.size).toBe(displayNames.length);

    // Both joined `id` fields must be prefixed (they collide with each other).
    const idFields = fields.filter((f) => f.name === "id");
    expect(idFields).toHaveLength(2);
    for (const f of idFields) {
      expect(f.displayName).toContain(".");
    }
    expect(idFields[0].displayName).not.toBe(idFields[1].displayName);
  });

  it("disambiguates 3-way collision: base id + join A id + join B id", () => {
    // The ticket's canonical repro: base has `id`, both joined tables have `id`.
    // All three must get unique prefixed display names.
    const base = makeTable("t-base", "leads", ["id", "name"]);
    const joinA = makeTable("t-a", "rooms", ["id", "label"]);
    const joinB = makeTable("t-b", "owners", ["id", "email"]);

    const joins: InsightJoinConfig[] = [
      {
        type: "inner",
        rightTableId: "t-a",
        leftKey: "room_id",
        rightKey: "id",
      },
      {
        type: "inner",
        rightTableId: "t-b",
        leftKey: "owner_id",
        rightKey: "id",
      },
    ];

    const { fields } = computeCombinedFields(base, joins, [base, joinA, joinB]);
    const idFields = fields.filter((f) => f.name === "id");
    expect(idFields).toHaveLength(3);

    // Every id field must carry a prefix.
    for (const f of idFields) {
      expect(f.displayName).toContain(".");
    }

    // All three display names must be distinct.
    const names = idFields.map((f) => f.displayName);
    expect(new Set(names).size).toBe(3);
  });

  // base[id], joinA[id, status], joinB[status] — every displayName must be unique
  it("base[id], joinA[id,status], joinB[status] — all displayNames unique", () => {
    const base = makeTable("t-base", "users", ["id"]);
    const joinA = makeTable("t-a", "orders", ["id", "status"]);
    const joinB = makeTable("t-b", "logs", ["status"]);

    const joins: InsightJoinConfig[] = [
      { type: "inner", rightTableId: "t-a", leftKey: "id", rightKey: "id" },
      {
        type: "inner",
        rightTableId: "t-b",
        leftKey: "order_id",
        rightKey: "status",
      },
    ];

    const { fields } = computeCombinedFields(base, joins, [base, joinA, joinB]);
    const displayNames = fields.map((f) => f.displayName);
    const unique = new Set(displayNames);
    expect(unique.size).toBe(displayNames.length);
  });

  it("post-prefix seen-set guard: two joined tables whose names shorten to the same prefix still produce unique displayNames", () => {
    // Two tables named "data_<uuid1>" and "data_<uuid2>" both shorten to "data"
    // via shortenAutoGeneratedName. Without the seen-set guard, both would emit
    // "data.id" — a duplicate even after count-based prefixing.
    const uuid1 = "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa";
    const uuid2 = "bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb";
    const base = makeTable("t-base", "events", ["name"]);
    const joinA = makeTable("t-a", `data_${uuid1}`, ["id", "label"]);
    const joinB = makeTable("t-b", `data_${uuid2}`, ["id", "value"]);

    const joins: InsightJoinConfig[] = [
      { type: "inner", rightTableId: "t-a", leftKey: "a_id", rightKey: "id" },
      { type: "inner", rightTableId: "t-b", leftKey: "b_id", rightKey: "id" },
    ];

    const { fields } = computeCombinedFields(base, joins, [base, joinA, joinB]);
    const displayNames = fields.map((f) => f.displayName);
    const unique = new Set(displayNames);
    expect(unique.size).toBe(displayNames.length);

    // Both `id` fields must have unique display names.
    const idFields = fields.filter((f) => f.name === "id");
    expect(idFields).toHaveLength(2);
    expect(idFields[0].displayName).not.toBe(idFields[1].displayName);
  });

  it("widens the suffix when colliding fields also share a field-id prefix", () => {
    // Pathological double-collision: three joined tables all shorten to the
    // same display prefix ("data"), so all three `id` fields compute "data.id".
    // Two of them ALSO share the first 4 chars of their field id ("shar"), so
    // the short 4-char suffix would still collide. The post-prefix guard must
    // widen the suffix until every name is unique.
    const u1 = "11111111-1111-4111-1111-111111111111";
    const u2 = "22222222-2222-4222-2222-222222222222";
    const u3 = "33333333-3333-4333-3333-333333333333";
    // Field ids are `${tableId}-id`. joinB and joinC share the "shar" prefix.
    const base = makeTable("t-base", "events", ["name"]);
    const joinA = makeTable("t-a", `data_${u1}`, ["id", "label"]);
    const joinB = makeTable("shared-bbbb", `data_${u2}`, ["id", "value"]);
    const joinC = makeTable("shared-cccc", `data_${u3}`, ["id", "note"]);

    const joins: InsightJoinConfig[] = [
      { type: "inner", rightTableId: "t-a", leftKey: "a_id", rightKey: "id" },
      {
        type: "inner",
        rightTableId: "shared-bbbb",
        leftKey: "b_id",
        rightKey: "id",
      },
      {
        type: "inner",
        rightTableId: "shared-cccc",
        leftKey: "c_id",
        rightKey: "id",
      },
    ];

    const { fields } = computeCombinedFields(base, joins, [
      base,
      joinA,
      joinB,
      joinC,
    ]);
    const displayNames = fields.map((f) => f.displayName);
    // Every display name unique — including the two sharing the "shar" id prefix.
    expect(new Set(displayNames).size).toBe(displayNames.length);

    const idFields = fields.filter((f) => f.name === "id");
    expect(idFields).toHaveLength(3);
    expect(new Set(idFields.map((f) => f.displayName)).size).toBe(3);
  });
});

function field(overrides: Partial<CombinedField>): CombinedField {
  return {
    id: overrides.id ?? `id-${overrides.name ?? "f"}`,
    name: overrides.name ?? "f",
    type: "string",
    columnName: overrides.columnName,
    sourceTableId: overrides.sourceTableId ?? "table-base",
    displayName: overrides.displayName ?? overrides.name ?? "f",
    ...overrides,
  } as CombinedField;
}

describe("computeFilterableFields", () => {
  it("returns all fields unchanged when there are no joins", () => {
    const fields = [
      field({ id: "a", name: "amount", columnName: "amount" }),
      field({ id: "b", name: "region", columnName: "region" }),
    ];
    expect(computeFilterableFields(fields, undefined)).toHaveLength(2);
  });

  it("excludes the right-side join key (dropped from the emitted subquery)", () => {
    // The joined table's `room_id` is joined on join.rightKey and dropped from
    // the subquery — a filter on it would silently resolve to a missing column.
    const fields = [
      field({ id: "lead-id", name: "lead_id", columnName: "lead_id" }),
      field({
        id: "room-id",
        name: "room_id",
        columnName: "room_id",
        sourceTableId: "table-rooms",
      }),
      field({
        id: "room-name",
        name: "room_name",
        columnName: "room_name",
        sourceTableId: "table-rooms",
      }),
    ];
    const joins: InsightJoinConfig[] = [
      {
        type: "inner",
        rightTableId: "table-rooms",
        leftKey: "lead_id",
        rightKey: "room_id",
      },
    ];
    const result = computeFilterableFields(fields, joins);
    expect(result.map((f) => f.columnName)).toEqual(["lead_id", "room_name"]);
    expect(result.some((f) => f.columnName === "room_id")).toBe(false);
  });

  it("matches the right join key case-insensitively", () => {
    const fields = [
      field({ id: "k", name: "ID", columnName: "ID", sourceTableId: "t2" }),
      field({
        id: "x",
        name: "label",
        columnName: "label",
        sourceTableId: "t2",
      }),
    ];
    const joins: InsightJoinConfig[] = [
      {
        type: "inner",
        rightTableId: "t2",
        leftKey: "fk",
        rightKey: "id", // lower-case, field is "ID"
      },
    ];
    const result = computeFilterableFields(fields, joins);
    expect(result.some((f) => f.columnName === "ID")).toBe(false);
  });

  it("excludes both sides of an ambiguous duplicate column name", () => {
    // Base `id` and joined `id` both persist the bare value "id"; the resolver
    // cannot disambiguate, so neither may be offered.
    const fields = [
      field({ id: "base-id", name: "id", columnName: "id" }),
      field({
        id: "join-id",
        name: "id",
        columnName: "id",
        sourceTableId: "t2",
        displayName: "rooms.id",
      }),
      field({ id: "amount", name: "amount", columnName: "amount" }),
    ];
    // No join key dropping in play here (rightKey unrelated).
    const joins: InsightJoinConfig[] = [
      {
        type: "inner",
        rightTableId: "t2",
        leftKey: "amount",
        rightKey: "amount_ref",
      },
    ];
    const result = computeFilterableFields(fields, joins);
    expect(result.map((f) => f.columnName)).toEqual(["amount"]);
  });

  it("keeps a base column whose name matches a dropped joined join-key", () => {
    // Base `id` and joined `id` share a name, and the join's rightKey IS `id`.
    // The JOINED `id` is the dropped right join-key and must be excluded — but
    // the BASE `id` stays in the emitted query, is unambiguous once the joined
    // key is gone, and MUST remain filterable. (Regression: an earlier version
    // dropped every field whose name matched any rightKey, hiding the base id.)
    const fields = [
      field({ id: "base-id", name: "id", columnName: "id" }), // base table
      field({
        id: "join-id",
        name: "id",
        columnName: "id",
        sourceTableId: "t2", // joined table — this is the right join-key
        displayName: "rooms.id",
      }),
      field({ id: "amount", name: "amount", columnName: "amount" }),
    ];
    const joins: InsightJoinConfig[] = [
      {
        type: "inner",
        rightTableId: "t2",
        leftKey: "id",
        rightKey: "id",
      },
    ];
    const result = computeFilterableFields(fields, joins);
    // Base `id` survives (and is the only `id` left, so unambiguous); the
    // joined `id` is dropped as the right join-key.
    expect(result.map((f) => f.id).sort()).toEqual(["amount", "base-id"]);
    const ids = result.filter((f) => f.columnName === "id");
    expect(ids).toHaveLength(1);
    expect(ids[0].id).toBe("base-id");
  });
});
