/**
 * @dashframe/engine-browser
 *
 * Browser implementation of DashFrame engine using DuckDB-WASM.
 *
 * This package provides:
 * - BrowserDataFrame: DataFrame implementation with IndexedDB storage
 * - QueryBuilder: SQL query builder for DuckDB-WASM
 * - IndexedDBStorage: Arrow IPC buffer storage
 * - Insight: Query configuration and SQL generation
 * - Analysis utilities
 *
 * Re-exports all types from @dashframe/engine for convenience.
 */

// Re-export all from @dashframe/engine
export * from "@dashframe/engine";

// ============================================================================
// DataFrame Implementation
// ============================================================================

export {
  BrowserDataFrame,
  BrowserDataFrame as DataFrame,
  browserDataFrameFactory,
} from "./dataframe";

// ============================================================================
// Storage Implementation
// ============================================================================

export {
  IndexedDBStorage,
  indexedDBStorage,
  // Legacy exports for backward compatibility
  persistArrowData,
  loadArrowData,
  deleteArrowData,
  generateArrowKey,
  extractDataFrameId,
} from "./storage";

// ============================================================================
// Query Builder
// ============================================================================

export {
  QueryBuilder,
  invalidateTableCache,
  clearAllTableCaches,
  ensureTableLoaded,
} from "./query-builder";

// ============================================================================
// Insight
// ============================================================================

export { Insight, shortenAutoGeneratedName } from "./insight";

export type {
  InsightConfiguration,
  InsightField,
  InsightMetricResolved,
  InsightJoin,
  DataTableField,
  DataTableInfo,
} from "./insight";

// ============================================================================
// Analysis Utilities
// ============================================================================

export {
  analyzeDataFrame,
  analyzeView,
  analyzeInsight,
  suggestJoinColumns,
  looksLikeIdentifier,
  CARDINALITY_THRESHOLDS,
  type ColumnCategory,
  type ColumnAnalysis,
  type JoinSuggestion,
} from "./analyze";
