/**
 * Shorten auto-generated table names by removing UUIDs and suffixes.
 */
export function shortenAutoGeneratedName(name: string): string {
  let cleaned = name.replace(/\.(csv|xlsx|json)$/i, "");
  cleaned = cleaned.replace(
    /[_-]?[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[_-]?/gi,
    "",
  );
  cleaned = cleaned.replace(/[_-]\d+$/, "");
  // oxlint-disable-next-line sonarjs/slow-regex -- anchored trim of leading/trailing underscores on a short identifier; no nested quantifier to backtrack
  cleaned = cleaned.replace(/(^_+)|(_+$)/g, "");
  return cleaned || name;
}
