/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../../packages/app/src/routes/__root'
import { Route as DataFramesRouteImport } from './../../../packages/app/src/routes/data-frames'
import { Route as IndexRouteImport } from './../../../packages/app/src/routes/index'
import { Route as DraftsIndexRouteImport } from './../../../packages/app/src/routes/drafts/index'
import { Route as DataSourcesIndexRouteImport } from './../../../packages/app/src/routes/data-sources/index'
import { Route as DashboardsIndexRouteImport } from './../../../packages/app/src/routes/dashboards/index'
import { Route as DataSourcesSourceIdRouteImport } from './../../../packages/app/src/routes/data-sources/$sourceId'
import { Route as DashboardsDashboardIdRouteImport } from './../../../packages/app/src/routes/dashboards/$dashboardId'
import { Route as DraftsDraftIdIndexRouteImport } from './../../../packages/app/src/routes/drafts/$draftId.index'
import { Route as DashboardsDashboardIdJoinInsightIdTableIdRouteImport } from './../../../packages/app/src/routes/dashboards/$dashboardId_.join.$insightId.$tableId'

const DataFramesRoute = DataFramesRouteImport.update({
  id: '/data-frames',
  path: '/data-frames',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsIndexRoute = DraftsIndexRouteImport.update({
  id: '/drafts/',
  path: '/drafts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesIndexRoute = DataSourcesIndexRouteImport.update({
  id: '/data-sources/',
  path: '/data-sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesSourceIdRoute = DataSourcesSourceIdRouteImport.update({
  id: '/data-sources/$sourceId',
  path: '/data-sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsDashboardIdRoute = DashboardsDashboardIdRouteImport.update({
  id: '/dashboards/$dashboardId',
  path: '/dashboards/$dashboardId',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsDraftIdIndexRoute = DraftsDraftIdIndexRouteImport.update({
  id: '/drafts/$draftId/',
  path: '/drafts/$draftId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsDashboardIdJoinInsightIdTableIdRoute =
  DashboardsDashboardIdJoinInsightIdTableIdRouteImport.update({
    id: '/dashboards/$dashboardId_/join/$insightId/$tableId',
    path: '/dashboards/$dashboardId/join/$insightId/$tableId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-frames': typeof DataFramesRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/data-sources/$sourceId': typeof DataSourcesSourceIdRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/data-sources/': typeof DataSourcesIndexRoute
  '/drafts/': typeof DraftsIndexRoute
  '/drafts/$draftId/': typeof DraftsDraftIdIndexRoute
  '/dashboards/$dashboardId/join/$insightId/$tableId': typeof DashboardsDashboardIdJoinInsightIdTableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-frames': typeof DataFramesRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/data-sources/$sourceId': typeof DataSourcesSourceIdRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/data-sources': typeof DataSourcesIndexRoute
  '/drafts': typeof DraftsIndexRoute
  '/drafts/$draftId': typeof DraftsDraftIdIndexRoute
  '/dashboards/$dashboardId/join/$insightId/$tableId': typeof DashboardsDashboardIdJoinInsightIdTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-frames': typeof DataFramesRoute
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRoute
  '/data-sources/$sourceId': typeof DataSourcesSourceIdRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/data-sources/': typeof DataSourcesIndexRoute
  '/drafts/': typeof DraftsIndexRoute
  '/drafts/$draftId/': typeof DraftsDraftIdIndexRoute
  '/dashboards/$dashboardId_/join/$insightId/$tableId': typeof DashboardsDashboardIdJoinInsightIdTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-frames'
    | '/dashboards/$dashboardId'
    | '/data-sources/$sourceId'
    | '/dashboards/'
    | '/data-sources/'
    | '/drafts/'
    | '/drafts/$draftId/'
    | '/dashboards/$dashboardId/join/$insightId/$tableId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-frames'
    | '/dashboards/$dashboardId'
    | '/data-sources/$sourceId'
    | '/dashboards'
    | '/data-sources'
    | '/drafts'
    | '/drafts/$draftId'
    | '/dashboards/$dashboardId/join/$insightId/$tableId'
  id:
    | '__root__'
    | '/'
    | '/data-frames'
    | '/dashboards/$dashboardId'
    | '/data-sources/$sourceId'
    | '/dashboards/'
    | '/data-sources/'
    | '/drafts/'
    | '/drafts/$draftId/'
    | '/dashboards/$dashboardId_/join/$insightId/$tableId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataFramesRoute: typeof DataFramesRoute
  DashboardsDashboardIdRoute: typeof DashboardsDashboardIdRoute
  DataSourcesSourceIdRoute: typeof DataSourcesSourceIdRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
  DataSourcesIndexRoute: typeof DataSourcesIndexRoute
  DraftsIndexRoute: typeof DraftsIndexRoute
  DraftsDraftIdIndexRoute: typeof DraftsDraftIdIndexRoute
  DashboardsDashboardIdJoinInsightIdTableIdRoute: typeof DashboardsDashboardIdJoinInsightIdTableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/data-frames': {
      id: '/data-frames'
      path: '/data-frames'
      fullPath: '/data-frames'
      preLoaderRoute: typeof DataFramesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts/': {
      id: '/drafts/'
      path: '/drafts'
      fullPath: '/drafts/'
      preLoaderRoute: typeof DraftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources/': {
      id: '/data-sources/'
      path: '/data-sources'
      fullPath: '/data-sources/'
      preLoaderRoute: typeof DataSourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources/$sourceId': {
      id: '/data-sources/$sourceId'
      path: '/data-sources/$sourceId'
      fullPath: '/data-sources/$sourceId'
      preLoaderRoute: typeof DataSourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId': {
      id: '/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof DashboardsDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts/$draftId/': {
      id: '/drafts/$draftId/'
      path: '/drafts/$draftId'
      fullPath: '/drafts/$draftId/'
      preLoaderRoute: typeof DraftsDraftIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$dashboardId_/join/$insightId/$tableId': {
      id: '/dashboards/$dashboardId_/join/$insightId/$tableId'
      path: '/dashboards/$dashboardId/join/$insightId/$tableId'
      fullPath: '/dashboards/$dashboardId/join/$insightId/$tableId'
      preLoaderRoute: typeof DashboardsDashboardIdJoinInsightIdTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataFramesRoute: DataFramesRoute,
  DashboardsDashboardIdRoute: DashboardsDashboardIdRoute,
  DataSourcesSourceIdRoute: DataSourcesSourceIdRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
  DataSourcesIndexRoute: DataSourcesIndexRoute,
  DraftsIndexRoute: DraftsIndexRoute,
  DraftsDraftIdIndexRoute: DraftsDraftIdIndexRoute,
  DashboardsDashboardIdJoinInsightIdTableIdRoute:
    DashboardsDashboardIdJoinInsightIdTableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
