#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for QueryBuilder Test Coverage Task

set -e

echo "========================================"
echo "QueryBuilder Test Coverage - Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/youhaowei/Projects/DashFrame"
cd "$PROJECT_ROOT"

echo ""
echo "Verifying project setup..."

# ============================================
# CHECK DEPENDENCIES
# ============================================

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    bun install
else
    echo -e "${GREEN}Dependencies already installed${NC}"
fi

# ============================================
# VERIFY PACKAGE STRUCTURE
# ============================================

echo ""
echo "Checking engine-browser package..."

if [ -d "packages/engine-browser/src" ]; then
    echo -e "${GREEN}engine-browser package found${NC}"
else
    echo -e "${RED}Error: engine-browser package not found${NC}"
    exit 1
fi

# Check for source files
if [ -f "packages/engine-browser/src/query-builder.ts" ]; then
    echo -e "${GREEN}query-builder.ts found (532 lines)${NC}"
else
    echo -e "${RED}Error: query-builder.ts not found${NC}"
    exit 1
fi

if [ -f "packages/engine-browser/src/insight.ts" ]; then
    echo -e "${GREEN}insight.ts found (506 lines)${NC}"
else
    echo -e "${RED}Error: insight.ts not found${NC}"
    exit 1
fi

# ============================================
# CHECK EXISTING TESTS
# ============================================

echo ""
echo "Checking for existing tests..."

if [ -f "packages/engine-browser/src/query-builder.test.ts" ]; then
    echo -e "${YELLOW}query-builder.test.ts already exists${NC}"
else
    echo -e "${GREEN}query-builder.test.ts needs to be created${NC}"
fi

if [ -f "packages/engine-browser/src/insight.test.ts" ]; then
    echo -e "${YELLOW}insight.test.ts already exists${NC}"
else
    echo -e "${GREEN}insight.test.ts needs to be created${NC}"
fi

# ============================================
# REFERENCE PATTERNS
# ============================================

echo ""
echo "Reference test patterns available at:"
echo "  - packages/connector-csv/src/connector.test.ts"
echo "  - packages/connector-csv/vitest.config.ts"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Files to Create:"
echo "  1. packages/engine-browser/vitest.config.ts"
echo "  2. packages/engine-browser/src/query-builder.test.ts"
echo "  3. packages/engine-browser/src/insight.test.ts"
echo ""
echo "Test Command:"
echo "  cd packages/engine-browser && npm run test"
echo ""
echo "Monorepo Test Command:"
echo "  npx turbo run test --filter=@dashframe/engine-browser"
echo ""
