/* eslint-disable sonarjs/cognitive-complexity */

import { useDuckDB } from "@/components/providers/DuckDBProvider";
import { useDataFramePagination } from "@/hooks/useDataFramePagination";
import {
  getDataFrame,
  useDataTables,
  useInsightMutations,
  useInsights,
} from "@dashframe/core";
import {
  quoteIdentifier,
  shortenAutoGeneratedName,
} from "@dashframe/engine-browser";
import type {
  DataFrameRow,
  DataTable,
  Field,
  InsightJoinConfig,
} from "@dashframe/types";
import {
  VirtualTable,
  type VirtualTableColumn,
  type VirtualTableColumnConfig,
} from "@dashframe/ui";
import { useNavigate } from "@tanstack/react-router";
import {
  Alert,
  AlertDescription,
  Button,
  Label,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  Spinner,
  Surface,
} from "@wystack/ui";
import { AlertCircleIcon, ArrowLeftIcon, MergeIcon } from "@wystack/ui-icons";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  findExistingJoinsToTable,
  isExactDuplicateJoin,
} from "./join-duplicate-guard";
import {
  createLatestRunGuard,
  runJoinSubmit,
  type LatestRunGuard,
} from "./join-preview-run";

interface JoinConfigureContentProps {
  insightId: string;
  tableId: string;
}

/** Local type for join preview result (static data for VirtualTable) */
interface JoinPreviewData {
  columns: VirtualTableColumn[];
  rows: DataFrameRow[];
}

const PREVIEW_ROW_LIMIT = 50;

/**
 * Join Configuration Page
 *
 * Provides a full-page experience for configuring joins between two tables:
 * - Side-by-side table previews (responsive: stacked on narrow screens)
 * - Column selection for join keys
 * - Join type selection
 * - Live preview of join result
 */
export default function JoinConfigureContent({
  insightId,
  tableId: joinTableId,
}: JoinConfigureContentProps) {
  const navigate = useNavigate();

  const { data: allInsights, isLoading: isInsightsLoading } = useInsights();
  const { data: allDataTables, isLoading: isTablesLoading } = useDataTables();
  const { update: updateInsight } = useInsightMutations();

  const isLoading = isInsightsLoading || isTablesLoading;

  // Find the current insight
  const insight = useMemo(
    () => allInsights?.find((i) => i.id === insightId),
    [allInsights, insightId],
  );

  // Join configuration state
  const [leftFieldId, setLeftFieldId] = useState<string | null>(null);
  const [rightFieldId, setRightFieldId] = useState<string | null>(null);
  const [joinType, setJoinType] = useState<
    "inner" | "left" | "right" | "outer"
  >("inner");
  const intersectionFill = useMemo(() => {
    if (joinType === "inner") {
      return "rgba(251, 191, 36, 0.5)";
    }

    if (joinType === "left" || joinType === "right") {
      return "rgba(251, 191, 36, 0.3)";
    }

    return "rgba(251, 191, 36, 0.2)";
  }, [joinType]);
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  // Preview result is wrapped with the input key it was computed against,
  // so stale results from a previous selection are ignored during render
  // rather than synchronously reset inside the compute effect.
  const [previewState, setPreviewState] = useState<{
    key: string;
    value: JoinPreviewData | null;
    totalCount: number;
  } | null>(null);
  const [isComputingPreview, setIsComputingPreview] = useState(false);
  // Stale-run guard for the preview compute effect. Lives in a ref so the same
  // guard instance tracks the latest run across re-renders. Its abandon() path
  // clears the spinner when a run is superseded with no successor (e.g. the
  // user clears a column selector), so the loading state can never stick. The
  // ref is only read inside the compute effect, never during render.
  const previewRunGuardRef = useRef<LatestRunGuard | null>(null);
  const previewKey =
    leftFieldId && rightFieldId ? `${leftFieldId}|${rightFieldId}` : null;
  const previewResult: JoinPreviewData | null =
    previewKey && previewState?.key === previewKey ? previewState.value : null;
  const previewTotalCount: number =
    previewKey && previewState?.key === previewKey
      ? previewState.totalCount
      : 0;
  const setPreviewResult = useCallback(
    (value: JoinPreviewData | null) => {
      if (previewKey) {
        setPreviewState((prev) => ({
          key: previewKey,
          value,
          totalCount: prev && prev.key === previewKey ? prev.totalCount : 0,
        }));
      }
    },
    [previewKey],
  );
  const setPreviewTotalCount = useCallback(
    (totalCount: number) => {
      if (previewKey) {
        setPreviewState((prev) => ({
          key: previewKey,
          value: prev && prev.key === previewKey ? prev.value : null,
          totalCount,
        }));
      }
    },
    [previewKey],
  );

  // Resolve base table (from insight's baseTableId)
  const baseTable = useMemo(() => {
    if (!insight || !allDataTables) return null;
    return allDataTables.find((t) => t.id === insight.baseTableId) ?? null;
  }, [insight, allDataTables]);

  // Resolve join table (from tableId param)
  const joinTable = useMemo(() => {
    if (!allDataTables) return null;
    return allDataTables.find((t) => t.id === joinTableId) ?? null;
  }, [allDataTables, joinTableId]);

  // DuckDB connection for join preview (initialized by DuckDBProvider during idle time)
  const {
    connection,
    isInitialized: isDuckDBReady,
    isLoading: isDuckDBLoading,
  } = useDuckDB();

  // Pagination hooks for async VirtualTable (full dataset browsing)
  const {
    fetchData: fetchBaseData,
    totalCount: baseTotalCount,
    isReady: isBaseReady,
  } = useDataFramePagination(baseTable?.dataFrameId);

  const {
    fetchData: fetchJoinData,
    totalCount: joinTotalCount,
    isReady: isJoinReady,
  } = useDataFramePagination(joinTable?.dataFrameId);

  // Filter out internal fields (those starting with _)
  const baseFields = useMemo(
    () => baseTable?.fields?.filter((f) => !f.name.startsWith("_")) ?? [],
    [baseTable],
  );

  const joinFields = useMemo(
    () => joinTable?.fields?.filter((f) => !f.name.startsWith("_")) ?? [],
    [joinTable],
  );

  // Detect existing joins to this right table so the UI can label instances.
  // A non-empty list means the user is adding a second (or further) join to the
  // same table — legitimate (e.g. orders→users on created_by AND approved_by),
  // but the UI must disambiguate the instances clearly.
  const existingJoinsToThisTable = useMemo(
    () => findExistingJoinsToTable(insight?.joins, joinTableId),
    [insight?.joins, joinTableId],
  );

  // Normalise the UI join type ("outer") to the stored config type ("full").
  // Used in both duplicate detection and persist — single source of truth.
  const toConfigType = useCallback(
    (t: typeof joinType): InsightJoinConfig["type"] =>
      t === "outer" ? "full" : t,
    [],
  );

  // Exact-duplicate detection: same table + same keys + same type.
  // Not a hard block — just surfaces a non-blocking warning so the user knows
  // they are adding a redundant join rather than a different-key one.
  const isExactDuplicate = useMemo(() => {
    if (!leftFieldId || !rightFieldId || existingJoinsToThisTable.length === 0)
      return false;
    const leftField = baseFields.find((f) => f.id === leftFieldId);
    const rightField = joinFields.find((f) => f.id === rightFieldId);
    if (!leftField || !rightField) return false;
    const leftKey = leftField.columnName ?? leftField.name;
    const rightKey = rightField.columnName ?? rightField.name;
    return isExactDuplicateJoin(existingJoinsToThisTable, {
      leftKey,
      rightKey,
      type: toConfigType(joinType),
    });
  }, [
    leftFieldId,
    rightFieldId,
    existingJoinsToThisTable,
    baseFields,
    joinFields,
    joinType,
    toConfigType,
  ]);

  // Column configs for highlighting selected columns in source tables
  const baseColumnConfigs = useMemo((): VirtualTableColumnConfig[] => {
    const leftField = baseFields.find((f) => f.id === leftFieldId);
    if (!leftField) return [];
    return [{ id: leftField.columnName ?? leftField.name, highlight: true }];
  }, [baseFields, leftFieldId]);

  const joinColumnConfigs = useMemo((): VirtualTableColumnConfig[] => {
    const rightField = joinFields.find((f) => f.id === rightFieldId);
    if (!rightField) return [];
    return [{ id: rightField.columnName ?? rightField.name, highlight: true }];
  }, [joinFields, rightFieldId]);

  // Column configs for the preview result - highlight base vs join columns
  const previewColumnConfigs = useMemo((): VirtualTableColumnConfig[] => {
    if (!previewResult?.columns || !baseTable || !joinTable) return [];

    // Get column names from each source table
    const baseColumnNames = new Set(
      baseFields.map((f) => f.columnName ?? f.name),
    );
    const joinColumnNames = new Set(
      joinFields.map((f) => f.columnName ?? f.name),
    );

    // Get table display names for prefix detection (must match SQL generation)
    const baseDisplayName = shortenAutoGeneratedName(baseTable.name);
    const joinDisplayName = shortenAutoGeneratedName(joinTable.name);

    return previewResult.columns
      .filter((col) => !col.name.startsWith("_"))
      .map((col) => {
        // Check if this column came from base or join table
        // Handle table name prefix format: "tableName.columnName"
        const hasBasePrefix = col.name.startsWith(`${baseDisplayName}.`);
        const hasJoinPrefix = col.name.startsWith(`${joinDisplayName}.`);

        // Determine highlight variant
        // If column has a prefix, it's definitively from ONE table only
        // (the prefix was added to disambiguate duplicate column names)
        let highlight: "base" | "join" | "both" | undefined;
        if (hasBasePrefix) {
          highlight = "base";
        } else if (hasJoinPrefix) {
          highlight = "join";
        } else {
          // No prefix - check which table(s) this column belongs to
          const isFromBase = baseColumnNames.has(col.name);
          const isFromJoin = joinColumnNames.has(col.name);

          if (isFromBase && isFromJoin) {
            // Column name exists in both original tables, but check if the other
            // table's version was prefixed (meaning this unprefixed one is from just one table)
            const hasBasePrefixedVersion = previewResult.columns.some(
              (c) => c.name === `${baseDisplayName}.${col.name}`,
            );
            const hasJoinPrefixedVersion = previewResult.columns.some(
              (c) => c.name === `${joinDisplayName}.${col.name}`,
            );

            if (hasJoinPrefixedVersion) {
              // Join table's version was prefixed, so unprefixed is from base only
              highlight = "base";
            } else if (hasBasePrefixedVersion) {
              // Base table's version was prefixed, so unprefixed is from join only
              highlight = "join";
            } else {
              // Neither was prefixed - genuinely in both (rare, e.g., join key)
              highlight = "both";
            }
          } else if (isFromBase) {
            highlight = "base";
          } else if (isFromJoin) {
            highlight = "join";
          }
        }

        return {
          id: col.name,
          highlight,
        };
      })
      .filter(
        (config) => config.highlight !== undefined,
      ) as VirtualTableColumnConfig[];
  }, [previewResult, baseTable, joinTable, baseFields, joinFields]);

  // Join analysis results for Venn diagram visualization. Keyed by the
  // selected field pair so stale results are ignored during render rather
  // than reset via setState-in-effect.
  type JoinAnalysisData = {
    baseUniqueCount: number;
    joinUniqueCount: number;
    matchingCount: number;
    estimatedResultRows: number;
  };
  const [joinAnalysisState, setJoinAnalysisState] = useState<{
    key: string;
    value: JoinAnalysisData | null;
  } | null>(null);
  const joinAnalysisKey =
    leftFieldId && rightFieldId ? `${leftFieldId}|${rightFieldId}` : null;
  const joinAnalysis: JoinAnalysisData | null =
    joinAnalysisKey && joinAnalysisState?.key === joinAnalysisKey
      ? joinAnalysisState.value
      : null;
  const setJoinAnalysis = useCallback(
    (value: JoinAnalysisData | null) => {
      if (joinAnalysisKey) {
        setJoinAnalysisState({ key: joinAnalysisKey, value });
      }
    },
    [joinAnalysisKey],
  );

  // Find columns with matching names (for suggestions) with analysis. Keyed
  // by `${baseDataFrameId}|${joinDataFrameId}` so a stale result from a
  // previous table pair is ignored during render rather than reset via
  // setState-in-effect.
  type SuggestionRow = {
    leftField: (typeof baseFields)[0];
    rightField: (typeof joinFields)[0];
    columnName: string;
    matchingValues: number;
    baseUniqueValues: number;
  };
  const [suggestionsState, setSuggestionsState] = useState<{
    key: string;
    rows: SuggestionRow[];
  } | null>(null);
  const suggestionsKey =
    baseTable?.dataFrameId && joinTable?.dataFrameId
      ? `${baseTable.dataFrameId}|${joinTable.dataFrameId}`
      : null;
  const columnSuggestions: SuggestionRow[] =
    suggestionsState && suggestionsState.key === suggestionsKey
      ? suggestionsState.rows
      : [];
  const setColumnSuggestions = useCallback(
    (rows: SuggestionRow[]) => {
      if (suggestionsKey) {
        setSuggestionsState({ key: suggestionsKey, rows });
      }
    },
    [suggestionsKey],
  );

  // Analyze matching columns for suggestions
  // DuckDB is lazy-loaded, so we check isDuckDBLoading before running analysis
  useEffect(() => {
    if (isDuckDBLoading || !connection || !isDuckDBReady) return;
    if (!baseTable?.dataFrameId || !joinTable?.dataFrameId) return;
    // Wait for pagination hooks to be ready (they load the data into DuckDB)
    if (!isBaseReady || !isJoinReady) return;

    const baseColMap = new Map<
      string,
      { field: (typeof baseFields)[0]; name: string }
    >();
    for (const field of baseFields) {
      const colName = field.columnName ?? field.name;
      baseColMap.set(colName.toLowerCase(), { field, name: colName });
    }

    const pairs: Array<{
      leftField: (typeof baseFields)[0];
      rightField: (typeof joinFields)[0];
      columnName: string;
    }> = [];
    for (const joinField of joinFields) {
      const joinColName = joinField.columnName ?? joinField.name;
      const baseMatch = baseColMap.get(joinColName.toLowerCase());
      if (baseMatch) {
        pairs.push({
          leftField: baseMatch.field,
          rightField: joinField,
          columnName: joinColName,
        });
      }
    }

    if (pairs.length === 0) {
      // No matching pairs — handled by the suggestionsKey gate at render.
      return;
    }

    const baseTableName = `df_${baseTable.dataFrameId!.replace(/-/g, "_")}`;
    const joinTableName = `df_${joinTable.dataFrameId!.replace(/-/g, "_")}`;

    const analyze = async () => {
      try {
        // Tables are already loaded by the pagination hooks

        const results: typeof columnSuggestions = [];

        for (const pair of pairs) {
          const leftColName = pair.leftField.columnName ?? pair.leftField.name;
          const rightColName =
            pair.rightField.columnName ?? pair.rightField.name;

          const sql = `
            WITH base_vals AS (SELECT DISTINCT ${quoteIdentifier(leftColName)} as val FROM ${quoteIdentifier(baseTableName)}),
            join_vals AS (SELECT DISTINCT ${quoteIdentifier(rightColName)} as val FROM ${quoteIdentifier(joinTableName)})
            SELECT
              (SELECT COUNT(*) FROM base_vals) as base_unique,
              (SELECT COUNT(*) FROM base_vals b WHERE EXISTS (SELECT 1 FROM join_vals j WHERE j.val = b.val)) as matching
          `;

          const result = await connection.query(sql);
          const row = result.toArray()[0] as {
            base_unique: number;
            matching: number;
          };

          results.push({
            ...pair,
            matchingValues: Number(row?.matching ?? 0),
            baseUniqueValues: Number(row?.base_unique ?? 0),
          });
        }

        // Sort by matching values (higher = better)
        results.sort((a, b) => b.matchingValues - a.matchingValues);
        setColumnSuggestions(results);
      } catch (err) {
        console.error("Failed to analyze column suggestions:", err);
        // Fallback without analysis
        setColumnSuggestions(
          pairs.map((p) => ({ ...p, matchingValues: 0, baseUniqueValues: 0 })),
        );
      }
    };

    analyze();
  }, [
    connection,
    isDuckDBReady,
    isDuckDBLoading,
    baseTable,
    joinTable,
    baseFields,
    joinFields,
    isBaseReady,
    isJoinReady,
    setColumnSuggestions,
  ]);

  // Apply a suggestion
  const applySuggestion = useCallback((pair: (typeof columnSuggestions)[0]) => {
    setLeftFieldId(pair.leftField.id);
    setRightFieldId(pair.rightField.id);
  }, []);

  // Analyze selected columns for Venn diagram
  // DuckDB is lazy-loaded, so we check isDuckDBLoading before running analysis
  useEffect(() => {
    // Empty selection is gated at render via joinAnalysisKey — no need to
    // synchronously reset state here.
    if (!leftFieldId || !rightFieldId) return;
    if (isDuckDBLoading || !connection || !isDuckDBReady) return;
    if (!baseTable?.dataFrameId || !joinTable?.dataFrameId) return;

    const leftField = baseFields.find((f) => f.id === leftFieldId);
    const rightField = joinFields.find((f) => f.id === rightFieldId);
    if (!leftField || !rightField) return;

    const leftColumnName = leftField.columnName ?? leftField.name;
    const rightColumnName = rightField.columnName ?? rightField.name;

    const analyze = async () => {
      try {
        const baseDataFrame = await getDataFrame(baseTable.dataFrameId!);
        const joinDataFrame = await getDataFrame(joinTable.dataFrameId!);
        if (!baseDataFrame || !joinDataFrame) return;

        await baseDataFrame.load(connection);
        await joinDataFrame.load(connection);

        const baseTableName = `df_${baseTable.dataFrameId!.replace(/-/g, "_")}`;
        const joinTableName = `df_${joinTable.dataFrameId!.replace(/-/g, "_")}`;

        // Get Venn diagram stats
        const vennSQL = `
          WITH base_values AS (
            SELECT DISTINCT ${quoteIdentifier(leftColumnName)} as val FROM ${quoteIdentifier(baseTableName)}
          ),
          join_values AS (
            SELECT DISTINCT ${quoteIdentifier(rightColumnName)} as val FROM ${quoteIdentifier(joinTableName)}
          ),
          matching AS (
            SELECT b.val FROM base_values b
            INNER JOIN join_values j ON b.val = j.val
          )
          SELECT
            (SELECT COUNT(*) FROM base_values) as base_unique,
            (SELECT COUNT(*) FROM join_values) as join_unique,
            (SELECT COUNT(*) FROM matching) as matching_count
        `;

        const vennResult = await connection.query(vennSQL);
        const vennRow = vennResult.toArray()[0] as {
          base_unique: number;
          join_unique: number;
          matching_count: number;
        };

        // Estimate result rows (for inner join)
        const countSQL = `
          SELECT COUNT(*) as cnt
          FROM ${quoteIdentifier(baseTableName)} b
          INNER JOIN ${quoteIdentifier(joinTableName)} j ON b.${quoteIdentifier(leftColumnName)} = j.${quoteIdentifier(rightColumnName)}
        `;
        const countResult = await connection.query(countSQL);
        const countRow = countResult.toArray()[0] as { cnt: number };

        setJoinAnalysis({
          baseUniqueCount: Number(vennRow?.base_unique ?? 0),
          joinUniqueCount: Number(vennRow?.join_unique ?? 0),
          matchingCount: Number(vennRow?.matching_count ?? 0),
          estimatedResultRows: Number(countRow?.cnt ?? 0),
        });
      } catch (err) {
        console.error("Failed to analyze join:", err);
        setJoinAnalysis(null);
      }
    };

    analyze();
  }, [
    leftFieldId,
    rightFieldId,
    connection,
    isDuckDBReady,
    isDuckDBLoading,
    baseTable,
    joinTable,
    baseFields,
    joinFields,
    setJoinAnalysis,
  ]);

  // Compute join preview using DuckDB (handles full dataset efficiently)
  // DuckDB is lazy-loaded, so we check isDuckDBLoading before computing preview
  useEffect(() => {
    // Empty selection is gated at render via previewKey — no need to
    // synchronously reset state here.
    if (!leftFieldId || !rightFieldId) return;

    if (isDuckDBLoading || !connection || !isDuckDBReady) {
      return;
    }

    if (!baseTable?.dataFrameId || !joinTable?.dataFrameId) {
      return;
    }

    const leftField = baseFields.find((f) => f.id === leftFieldId);
    const rightField = joinFields.find((f) => f.id === rightFieldId);

    if (!leftField || !rightField) {
      // Field lookup failed — leave the previous result untouched; the key
      // gate at render hides it if the inputs no longer match.
      return;
    }

    const leftColumnName = leftField.columnName ?? leftField.name;
    const rightColumnName = rightField.columnName ?? rightField.name;

    // Stale-run guard: begin() marks this the latest run and turns the spinner
    // on; run.isCurrent() is false once a newer run begins or this one is
    // abandoned by the cleanup below, gating all shared-state writes. Lazily
    // created once and reused across effect runs so the latest-run tracking is
    // shared (the ref is only touched here, never during render).
    const previewRunGuard = (previewRunGuardRef.current ??=
      createLatestRunGuard(setIsComputingPreview));
    const run = previewRunGuard.begin();

    const computeJoin = async () => {
      setError(null);
      try {
        const baseDataFrame = await getDataFrame(baseTable.dataFrameId!);
        const joinDataFrame = await getDataFrame(joinTable.dataFrameId!);

        // Stale-run guard: if a newer effect run has started, bail without
        // writing any React state.
        if (!run.isCurrent()) return;

        if (!baseDataFrame || !joinDataFrame) {
          setError("Could not load DataFrames");
          return;
        }

        // Load both tables into DuckDB (side effect ensures tables exist)
        await baseDataFrame.load(connection);
        await joinDataFrame.load(connection);

        // Stale-run guard: check again after every await.
        if (!run.isCurrent()) return;

        const baseTableName = `df_${baseTable.dataFrameId!.replace(/-/g, "_")}`;
        const joinTableName = `df_${joinTable.dataFrameId!.replace(/-/g, "_")}`;

        // Build the JOIN SQL
        const joinTypeSQL = joinType.toUpperCase();

        // Get column lists, handling duplicates with table name prefixes
        const baseColNames = baseFields.map((f) => f.columnName ?? f.name);
        const joinColNames = joinFields.map((f) => f.columnName ?? f.name);

        // Get display names for table prefixes (cleaned of UUIDs)
        const baseDisplayName = shortenAutoGeneratedName(baseTable.name);
        const joinDisplayName = shortenAutoGeneratedName(joinTable.name);

        // Build SELECT clause with table name prefixes for duplicate columns
        const selectParts: string[] = [];

        for (const col of baseColNames) {
          if (col.startsWith("_")) continue; // Skip internal columns
          const isDuplicate =
            joinColNames.includes(col) && col !== leftColumnName;
          if (isDuplicate) {
            // Use table name prefix: "accounts.acctid" instead of "acctid_base"
            const alias = quoteIdentifier(`${baseDisplayName}.${col}`);
            selectParts.push(`base.${quoteIdentifier(col)} AS ${alias}`);
          } else {
            selectParts.push(`base.${quoteIdentifier(col)}`);
          }
        }

        // Build lowercase set of base column names for case-insensitive duplicate detection
        const baseColNamesLower = new Set(
          baseColNames.map((c) => c.toLowerCase()),
        );

        for (const col of joinColNames) {
          if (col.startsWith("_")) continue; // Skip internal columns
          // For INNER joins, skip the join key column - it's redundant with base table's
          // join key (they have the same values for all matched rows).
          // For LEFT/RIGHT/OUTER joins, keep both since NULLs may differ.
          if (joinType === "inner" && col === rightColumnName) continue;
          // Check for duplicate using case-insensitive comparison
          // DuckDB treats column names case-insensitively, so "acctId" and "acctid" conflict
          const isDuplicate = baseColNamesLower.has(col.toLowerCase());
          if (isDuplicate) {
            // Use table name prefix: "opportunities.acctid" instead of "acctid_1"
            const alias = quoteIdentifier(`${joinDisplayName}.${col}`);
            selectParts.push(`j.${quoteIdentifier(col)} AS ${alias}`);
          } else {
            selectParts.push(`j.${quoteIdentifier(col)}`);
          }
        }

        // Table names are quoted at the point of use so the SQL sink is safe
        // regardless of where the dataFrameId-derived name came from.
        const joinSQL = `
          SELECT ${selectParts.join(", ")}
          FROM ${quoteIdentifier(baseTableName)} AS base
          ${joinTypeSQL} JOIN ${quoteIdentifier(joinTableName)} AS j
          ON base.${quoteIdentifier(leftColumnName)} = j.${quoteIdentifier(rightColumnName)}
          LIMIT ${PREVIEW_ROW_LIMIT}
        `;

        console.log("[JoinPreview] Executing DuckDB join:", joinSQL);

        const result = await connection.query(joinSQL);

        // Stale-run guard: last check before committing results to state.
        if (!run.isCurrent()) return;

        const rows = result.toArray() as DataFrameRow[];

        // Get total count for the join
        const countSQL = `
          SELECT COUNT(*) as count
          FROM ${quoteIdentifier(baseTableName)} AS base
          ${joinTypeSQL} JOIN ${quoteIdentifier(joinTableName)} AS j
          ON base.${quoteIdentifier(leftColumnName)} = j.${quoteIdentifier(rightColumnName)}
        `;
        const countResult = await connection.query(countSQL);

        if (!run.isCurrent()) return;

        const totalJoinCount = Number(countResult.toArray()[0]?.count ?? 0);

        // Build columns from the result
        const columns: VirtualTableColumn[] =
          rows.length > 0
            ? Object.keys(rows[0]!)
                .filter((key) => !key.startsWith("_"))
                .map((name) => ({ name }))
            : [];

        console.log("[JoinPreview] DuckDB result:", {
          previewRows: rows.length,
          totalJoinCount,
          columns: columns.length,
        });

        setPreviewResult({ columns, rows });
        // Store total count for display
        setPreviewTotalCount(totalJoinCount);
      } catch (err) {
        // Only surface the error if this run is still the active one.
        if (!run.isCurrent()) return;
        console.error("DuckDB join preview failed:", err);
        setPreviewResult(null);
        const errorMessage =
          err instanceof Error ? err.message : "Unknown error";
        setError(`Join preview failed: ${errorMessage}`);
      } finally {
        // Clear the spinner for the active run; a stale run leaves the newer
        // run's spinner alone (settle is a no-op when not current).
        run.settle();
      }
    };

    computeJoin();

    return () => {
      // Abandon this run: invalidate it so in-flight async callbacks become
      // no-ops, AND clear the spinner. If a successor effect run begins (deps
      // still warrant a compute) it re-sets the spinner synchronously; if none
      // does (e.g. the user cleared a column selector) the spinner unsticks.
      previewRunGuard.abandon();
    };
  }, [
    leftFieldId,
    rightFieldId,
    joinType,
    connection,
    isDuckDBReady,
    isDuckDBLoading,
    baseTable,
    joinTable,
    baseFields,
    joinFields,
    setPreviewResult,
    setPreviewTotalCount,
  ]);

  // Execute full join and add to existing insight
  // Note: We only store the join configuration here. The actual join is computed
  // on-demand when displaying the preview in InsightConfigureTab.
  const handleExecuteJoin = useCallback(async () => {
    if (!leftFieldId || !rightFieldId) {
      setError("Select both join columns.");
      return;
    }

    if (!baseTable || !joinTable || !insight) {
      setError("Unable to load table data.");
      return;
    }

    const leftField = baseFields.find((f) => f.id === leftFieldId);
    const rightField = joinFields.find((f) => f.id === rightFieldId);

    if (!leftField || !rightField) {
      setError("Selected columns are no longer available.");
      return;
    }

    setError(null);

    // Validate the join works by testing it (using preview result)
    // The preview is already computed, so we just check if it succeeded
    if (!previewResult || previewResult.rows.length === 0) {
      // Still allow the join even with 0 rows - user may want to keep the config
      // Just warn them in the UI (handled by the existing Alert component)
    }

    // runJoinSubmit owns the try/catch/finally: it always restores the button,
    // surfaces an error on rejection, and only navigates on success.
    await runJoinSubmit({
      persist: async () => {
        // Create join config using the Core schema
        // Uses column names (strings) as join keys, not field UUIDs
        const joinConfig: InsightJoinConfig = {
          type: toConfigType(joinType),
          rightTableId: joinTable.id,
          leftKey: leftField.columnName ?? leftField.name,
          rightKey: rightField.columnName ?? rightField.name,
        };

        // Add join to existing insight (append to existing joins if any)
        const existingJoins = insight.joins ?? [];
        await updateInsight(insightId, {
          joins: [...existingJoins, joinConfig],
        });

        // Note: We intentionally do NOT store a pre-computed joined DataFrame here.
        // The join preview in InsightConfigureTab computes the join on-demand,
        // which ensures we always show raw joined data (not aggregated data).
      },
      // Navigate back to the same insight only on success.
      onSuccess: () => navigate({ to: `/insights/${insightId}` } as never),
      setError,
      setSubmitting: setIsSubmitting,
    });
  }, [
    leftFieldId,
    rightFieldId,
    joinType,
    baseTable,
    joinTable,
    baseFields,
    joinFields,
    insight,
    insightId,
    updateInsight,
    previewResult,
    navigate,
    toConfigType,
  ]);

  // Loading state - wait for all stores to hydrate before rendering
  if (isLoading) {
    return (
      <div className="flex h-full items-center justify-center bg-neutral-bg">
        <div className="flex flex-col items-center gap-4">
          <Spinner size="lg" className="text-neutral-fg-subtle" />
          <p className="text-sm text-neutral-fg-subtle">
            Loading join configuration...
          </p>
        </div>
      </div>
    );
  }

  // Error states
  if (!insight) {
    return (
      <div className="flex h-full items-center justify-center bg-neutral-bg">
        <Surface elevation="raised" className="p-8 text-center">
          <AlertCircleIcon className="mx-auto mb-4 h-10 w-10 text-neutral-fg-subtle" />
          <h2 className="text-xl font-semibold">Insight not found</h2>
          <p className="mt-2 text-sm text-neutral-fg-subtle">
            The insight you&apos;re looking for doesn&apos;t exist.
          </p>
          <Button
            label="Go to Insights"
            onClick={() => navigate({ to: "/insights" })}
            className="mt-4"
          />
        </Surface>
      </div>
    );
  }

  if (!baseTable) {
    return (
      <div className="flex h-full items-center justify-center bg-neutral-bg">
        <Surface elevation="raised" className="p-8 text-center">
          <AlertCircleIcon className="mx-auto mb-4 h-10 w-10 text-neutral-fg-subtle" />
          <h2 className="text-xl font-semibold">Base table not found</h2>
          <p className="mt-2 text-sm text-neutral-fg-subtle">
            The data table for this insight no longer exists.
          </p>
          <Button
            label="Go to Insights"
            onClick={() => navigate({ to: "/insights" })}
            className="mt-4"
          />
        </Surface>
      </div>
    );
  }

  if (!joinTable) {
    return (
      <div className="flex h-full items-center justify-center bg-neutral-bg">
        <Surface elevation="raised" className="p-8 text-center">
          <AlertCircleIcon className="mx-auto mb-4 h-10 w-10 text-neutral-fg-subtle" />
          <h2 className="text-xl font-semibold">Join table not found</h2>
          <p className="mt-2 text-sm text-neutral-fg-subtle">
            The table you&apos;re trying to join with doesn&apos;t exist.
          </p>
          <Button
            label="Back to Insight"
            onClick={() => navigate({ to: `/insights/${insightId}` } as never)}
            className="mt-4"
          />
        </Surface>
      </div>
    );
  }

  const canJoin = leftFieldId && rightFieldId;

  return (
    <div className="flex h-full flex-col bg-neutral-bg">
      {/* Header */}
      <header className="sticky top-0 z-10 border-b bg-neutral-bg/90 backdrop-blur-sm">
        <div className="container mx-auto px-6 py-4">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <Button
                variant="ghost"
                icon={ArrowLeftIcon}
                label="Cancel"
                size="sm"
                onClick={() =>
                  navigate({ to: `/insights/${insightId}` } as never)
                }
              />
              <div>
                <h1 className="text-xl font-semibold">
                  {existingJoinsToThisTable.length > 0
                    ? `Join ${existingJoinsToThisTable.length + 1}: ${baseTable.name} + ${joinTable.name}`
                    : `Join: ${baseTable.name} + ${joinTable.name}`}
                </h1>
                <p className="text-sm text-neutral-fg-subtle">
                  Configure how to combine these datasets
                </p>
              </div>
            </div>
            <Button
              icon={MergeIcon}
              loading={isSubmitting}
              label={isSubmitting ? "Joining..." : "Join Tables"}
              onClick={handleExecuteJoin}
              disabled={!canJoin || isSubmitting}
            />
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 overflow-auto">
        <div className="container mx-auto space-y-6 px-6 py-6">
          {/* Dual Table Previews */}
          <div className="grid gap-6 md:grid-cols-2">
            {/* Base Table Preview */}
            <TablePreviewSection
              title="Base Table"
              table={baseTable}
              totalCount={baseTotalCount}
              isReady={isBaseReady}
              onFetchData={fetchBaseData}
              fields={baseTable.fields}
              columnConfigs={baseColumnConfigs}
              onHeaderClick={(colName) => {
                const field = baseFields.find(
                  (f) => (f.columnName ?? f.name) === colName,
                );
                if (field) setLeftFieldId(field.id);
              }}
            />

            {/* Join Table Preview */}
            <TablePreviewSection
              title="Join Table"
              table={joinTable}
              totalCount={joinTotalCount}
              isReady={isJoinReady}
              onFetchData={fetchJoinData}
              fields={joinTable.fields}
              columnConfigs={joinColumnConfigs}
              onHeaderClick={(colName) => {
                const field = joinFields.find(
                  (f) => (f.columnName ?? f.name) === colName,
                );
                if (field) setRightFieldId(field.id);
              }}
            />
          </div>

          {/* Join Configuration */}
          <Surface elevation="raised" className="rounded-2xl p-6">
            <h2 className="mb-4 text-lg font-semibold">Join Configuration</h2>

            {/* Existing-join disambiguation banner — only shown when this table
                is already joined to the insight at least once. Informs the user
                which keys the prior join(s) use so they can pick different ones
                for a legitimate double-join (e.g. created_by + approved_by). */}
            {existingJoinsToThisTable.length > 0 && (
              <div className="mb-4 rounded-xl border border-neutral-border/60 bg-neutral-bg-muted/50 p-4">
                <p className="mb-2 text-sm font-medium">
                  {joinTable.name} is already joined to this insight
                  {existingJoinsToThisTable.length > 1
                    ? ` (${existingJoinsToThisTable.length} times)`
                    : ""}
                </p>
                <ul className="space-y-1">
                  {existingJoinsToThisTable.map((j, i) => (
                    <li
                      key={`${j.leftKey}|${j.rightKey}|${j.type}|${i}`}
                      className="text-xs text-neutral-fg-subtle"
                    >
                      Join {i + 1}:{" "}
                      <span className="font-mono">{j.leftKey}</span>
                      {" = "}
                      <span className="font-mono">{j.rightKey}</span>
                      {" ("}
                      {j.type === "full" ? "outer" : j.type}
                      {")"}
                    </li>
                  ))}
                </ul>
                <p className="mt-2 text-xs text-neutral-fg-subtle">
                  Joining the same table on different keys is valid — for
                  example, <span className="font-mono">created_by</span> and{" "}
                  <span className="font-mono">approved_by</span> can both join
                  the same users table.
                </p>
              </div>
            )}

            {/* Matching column suggestions */}
            {columnSuggestions.length > 0 && (
              <div className="mb-6 rounded-xl border border-neutral-border/60 bg-neutral-bg-muted/50 p-4">
                <div className="mb-3 flex items-center gap-2">
                  <span className="text-sm font-medium">
                    Matching columns found
                  </span>
                  <span className="text-xs text-neutral-fg-subtle">
                    – click to select
                  </span>
                </div>
                <div className="flex flex-wrap gap-2">
                  {columnSuggestions.map((pair) => (
                    <button
                      key={pair.columnName}
                      type="button"
                      onClick={() => applySuggestion(pair)}
                      className="group flex cursor-pointer items-center gap-2 rounded-lg border border-neutral-border bg-neutral-bg px-3 py-2 text-sm transition-colors hover:border-palette-primary/50 hover:bg-palette-primary/10"
                    >
                      <span className="font-medium text-neutral-fg group-hover:text-palette-primary">
                        {pair.leftField.columnName ?? pair.leftField.name}
                      </span>
                      <span className="text-neutral-fg-subtle">↔</span>
                      <span className="font-medium text-neutral-fg group-hover:text-palette-primary">
                        {pair.rightField.columnName ?? pair.rightField.name}
                      </span>
                      {pair.matchingValues > 0 && (
                        <span className="ml-1 text-xs text-neutral-fg-subtle">
                          ({pair.matchingValues.toLocaleString()} matching)
                        </span>
                      )}
                    </button>
                  ))}
                </div>
              </div>
            )}

            <div className="grid gap-6 lg:grid-cols-2">
              {/* Column Selection */}
              <div className="space-y-4">
                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="left-column">Base table column</Label>
                    <Select
                      value={leftFieldId ?? ""}
                      onValueChange={(value) => setLeftFieldId(value || null)}
                    >
                      <SelectTrigger id="left-column">
                        <SelectValue placeholder="Select column..." />
                      </SelectTrigger>
                      <SelectContent>
                        {baseFields.map((field) => (
                          <SelectItem key={field.id} value={field.id}>
                            {field.name}
                            <span className="ml-2 text-xs text-neutral-fg-subtle">
                              ({field.type})
                            </span>
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="right-column">Join table column</Label>
                    <Select
                      value={rightFieldId ?? ""}
                      onValueChange={(value) => setRightFieldId(value || null)}
                    >
                      <SelectTrigger id="right-column">
                        <SelectValue placeholder="Select column..." />
                      </SelectTrigger>
                      <SelectContent>
                        {joinFields.map((field) => (
                          <SelectItem key={field.id} value={field.id}>
                            {field.name}
                            <span className="ml-2 text-xs text-neutral-fg-subtle">
                              ({field.type})
                            </span>
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="join-type">Join type</Label>
                  <Select
                    value={joinType}
                    onValueChange={(value) =>
                      setJoinType(value as "inner" | "left" | "right" | "outer")
                    }
                  >
                    <SelectTrigger id="join-type">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="inner">
                        Inner
                        <span className="ml-2 text-xs text-neutral-fg-subtle">
                          (only matching rows)
                        </span>
                      </SelectItem>
                      <SelectItem value="left">
                        Left
                        <span className="ml-2 text-xs text-neutral-fg-subtle">
                          (all base + matching)
                        </span>
                      </SelectItem>
                      <SelectItem value="right">
                        Right
                        <span className="ml-2 text-xs text-neutral-fg-subtle">
                          (matching + all join)
                        </span>
                      </SelectItem>
                      <SelectItem value="outer">
                        Outer
                        <span className="ml-2 text-xs text-neutral-fg-subtle">
                          (all rows from both)
                        </span>
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              {/* Venn Diagram Visualization */}
              {joinAnalysis && (
                <div className="flex flex-col items-center justify-center">
                  {/* SVG Venn Diagram */}
                  <svg
                    viewBox="0 0 200 120"
                    className="h-auto w-full max-w-[280px]"
                  >
                    {/* Base table circle (left) */}
                    <circle
                      cx="70"
                      cy="60"
                      r="45"
                      fill="rgba(59, 130, 246, 0.2)"
                      stroke="rgb(59, 130, 246)"
                      strokeWidth="2"
                    />
                    {/* Join table circle (right) */}
                    <circle
                      cx="130"
                      cy="60"
                      r="45"
                      fill="rgba(16, 185, 129, 0.2)"
                      stroke="rgb(16, 185, 129)"
                      strokeWidth="2"
                    />
                    {/* Intersection highlight based on join type */}
                    <clipPath id="leftClip">
                      <circle cx="70" cy="60" r="45" />
                    </clipPath>
                    <clipPath id="rightClip">
                      <circle cx="130" cy="60" r="45" />
                    </clipPath>
                    {/* Intersection area */}
                    <circle
                      cx="130"
                      cy="60"
                      r="45"
                      clipPath="url(#leftClip)"
                      fill={intersectionFill}
                      stroke="rgb(251, 191, 36)"
                      strokeWidth={joinType === "inner" ? "2" : "1"}
                    />
                    {/* Labels */}
                    <text
                      x="45"
                      y="60"
                      textAnchor="middle"
                      className="fill-blue-600 text-[10px] font-medium"
                    >
                      {(
                        joinAnalysis.baseUniqueCount -
                        joinAnalysis.matchingCount
                      ).toLocaleString()}
                    </text>
                    <text
                      x="100"
                      y="55"
                      textAnchor="middle"
                      className="fill-amber-600 text-[11px] font-bold"
                    >
                      {joinAnalysis.matchingCount.toLocaleString()}
                    </text>
                    <text
                      x="100"
                      y="68"
                      textAnchor="middle"
                      className="fill-amber-600 text-[8px]"
                    >
                      matching
                    </text>
                    <text
                      x="155"
                      y="60"
                      textAnchor="middle"
                      className="fill-emerald-600 text-[10px] font-medium"
                    >
                      {(
                        joinAnalysis.joinUniqueCount -
                        joinAnalysis.matchingCount
                      ).toLocaleString()}
                    </text>
                    {/* Circle labels */}
                    <text
                      x="45"
                      y="110"
                      textAnchor="middle"
                      className="fill-neutral-fg-subtle text-[9px]"
                    >
                      Base
                    </text>
                    <text
                      x="155"
                      y="110"
                      textAnchor="middle"
                      className="fill-neutral-fg-subtle text-[9px]"
                    >
                      Join
                    </text>
                  </svg>

                  {/* Result summary */}
                  <div className="mt-3 text-center">
                    <p className="text-sm font-medium">
                      {joinType === "inner" && (
                        <>
                          Result:{" "}
                          <span className="text-palette-warning">
                            {joinAnalysis.estimatedResultRows.toLocaleString()}
                          </span>{" "}
                          rows
                        </>
                      )}
                      {joinType === "left" && (
                        <>Result: all base rows + matched join data</>
                      )}
                      {joinType === "right" && (
                        <>Result: matched base data + all join rows</>
                      )}
                      {joinType === "outer" && (
                        <>Result: all rows from both tables</>
                      )}
                    </p>
                    <p className="mt-1 text-xs text-neutral-fg-subtle">
                      {joinAnalysis.matchingCount.toLocaleString()} of{" "}
                      {joinAnalysis.baseUniqueCount.toLocaleString()} base
                      values have matches
                    </p>
                  </div>
                </div>
              )}
            </div>
          </Surface>

          {/* Exact-duplicate warning — non-blocking; user can still submit */}
          {isExactDuplicate && (
            <Alert>
              <AlertDescription>
                These keys and join type are identical to an existing join on{" "}
                {joinTable.name}. The result will include duplicate columns.
                Choose different keys to join on a different relationship.
              </AlertDescription>
            </Alert>
          )}

          {/* Error Display */}
          {error && (
            <Alert color="danger">
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          {/* Preview Result */}
          {canJoin && (
            <Surface elevation="raised" className="rounded-2xl p-6">
              <div className="mb-4 flex items-center justify-between">
                <h2 className="text-lg font-semibold">Preview Result</h2>
                {isComputingPreview && (
                  <div className="flex items-center gap-2 text-sm text-neutral-fg-subtle">
                    <Spinner size="sm" />
                    Computing preview...
                  </div>
                )}
                {!isComputingPreview && previewResult && (
                  <p className="text-sm text-neutral-fg-subtle">
                    {previewTotalCount.toLocaleString()} total rows
                    {previewTotalCount > PREVIEW_ROW_LIMIT &&
                      ` (showing first ${PREVIEW_ROW_LIMIT})`}
                    {" · "}
                    {previewResult.columns?.length ?? 0} columns
                  </p>
                )}
              </div>

              {/* Preview result or placeholder */}
              {!isComputingPreview && previewResult && (
                <>
                  {/* Legend for column colors */}
                  <div className="mb-3 flex flex-wrap items-center gap-4 text-xs">
                    <div className="flex items-center gap-1.5">
                      <div className="h-3 w-3 rounded bg-palette-info" />
                      <span className="text-neutral-fg-subtle">
                        From {baseTable.name ?? "base table"}
                      </span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <div className="h-3 w-3 rounded bg-palette-success" />
                      <span className="text-neutral-fg-subtle">
                        From {joinTable.name ?? "join table"}
                      </span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <div className="h-3 w-3 rounded bg-palette-warning" />
                      <span className="text-neutral-fg-subtle">
                        In both tables
                      </span>
                    </div>
                  </div>
                  <div
                    className="overflow-hidden rounded-xl border border-neutral-border/60"
                    style={{ maxHeight: 300 }}
                  >
                    <VirtualTable
                      rows={previewResult.rows}
                      columns={previewResult.columns}
                      columnConfigs={previewColumnConfigs}
                      height={300}
                      compact
                    />
                  </div>
                </>
              )}
              {!isComputingPreview && !previewResult && (
                <div className="flex h-40 items-center justify-center text-neutral-fg-subtle">
                  {error
                    ? "Unable to generate preview"
                    : "Select join columns to see preview"}
                </div>
              )}

              {!isComputingPreview &&
                previewResult &&
                previewResult.rows.length === 0 && (
                  <Alert className="mt-4">
                    <AlertDescription>
                      This join produces 0 rows. Consider using a different join
                      type or checking that the columns have matching values.
                    </AlertDescription>
                  </Alert>
                )}
            </Surface>
          )}
        </div>
      </main>
    </div>
  );
}

// ============================================================================
// Table Preview Section Component
// ============================================================================

interface TablePreviewSectionProps {
  title: string;
  table: DataTable;
  totalCount: number;
  isReady: boolean;
  onFetchData: (
    params: import("@dashframe/ui").FetchDataParams,
  ) => Promise<import("@dashframe/ui").FetchDataResult>;
  fields: Field[];
  columnConfigs?: VirtualTableColumnConfig[];
  onHeaderClick?: (columnName: string) => void;
}

function TablePreviewSection({
  title,
  table,
  totalCount,
  isReady,
  onFetchData,
  fields,
  columnConfigs,
  onHeaderClick,
}: TablePreviewSectionProps) {
  const colCount = fields.filter((f) => !f.name.startsWith("_")).length;

  return (
    <Surface elevation="raised" className="overflow-hidden rounded-2xl">
      <div className="border-b border-neutral-border/60 px-4 py-3">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-xs tracking-wide text-neutral-fg-subtle uppercase">
              {title}
            </p>
            <p className="font-semibold">{table.name}</p>
          </div>
          <p className="text-xs text-neutral-fg-subtle">
            {totalCount.toLocaleString()} rows · {colCount} columns
          </p>
        </div>
        <p className="mt-1 text-xs text-neutral-fg-subtle">
          Click a column header to select it for joining
        </p>
      </div>
      <div style={{ height: 260 }} className="overflow-hidden">
        {!isReady ? (
          <div className="flex h-40 items-center justify-center text-neutral-fg-subtle">
            <div className="flex flex-col items-center gap-2">
              <Spinner size="lg" />
              <span className="text-sm">Loading data...</span>
            </div>
          </div>
        ) : (
          <VirtualTable
            onFetchData={onFetchData}
            columnConfigs={columnConfigs}
            height={260}
            onHeaderClick={onHeaderClick}
            compact
          />
        )}
      </div>
    </Surface>
  );
}
