/**
 * Unit tests for useInsightPagination hook — result-set field collection
 *
 * Contract: columnDisplayNames and columnTypeMap must NOT contain entries for
 * right join-key fields that buildInsightSQL drops from the emitted subquery.
 * Before this fix, allFields was assembled from raw table fields, which included
 * the right join-key. The maps built from those stale entries let VirtualTable
 * resolve the wrong display name or type for UUID aliases that don't exist in
 * the result set.
 *
 * Fix: allFields now drops ONLY the right join-key fields (the columns
 * processSingleJoin excludes from SELECT) before being stored in resolvedFields
 * (the source for both maps).  It deliberately does NOT apply the full
 * computeFilterableFields narrowing — that function's step 2 also drops fields
 * with an ambiguous bare column name, but those still appear in the SQL result
 * under distinct UUID aliases and must keep their display-name and type entries.
 */
import type { DataTable, Field, Insight, UUID } from "@dashframe/types";
import { renderHook, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { useInsightPagination } from "./useInsightPagination";

// ---------------------------------------------------------------------------
// Hoisted mocks
// ---------------------------------------------------------------------------

const {
  mockQuery,
  mockConnection,
  mockUseDuckDB,
  mockGetDataFrame,
  mockGetDataTable,
  mockBuildInsightSQL,
  mockEnsureTableLoaded,
} = vi.hoisted(() => {
  const query = vi.fn();
  const connection = { query };
  const useDuckDB = vi.fn();
  return {
    mockQuery: query,
    mockConnection: connection,
    mockUseDuckDB: useDuckDB,
    mockGetDataFrame: vi.fn(),
    mockGetDataTable: vi.fn(),
    mockBuildInsightSQL: vi.fn(),
    mockEnsureTableLoaded: vi.fn(),
  };
});

vi.mock("@/components/providers/DuckDBProvider", () => ({
  useDuckDB: () => mockUseDuckDB(),
}));

vi.mock("@dashframe/core", () => ({
  getDataFrame: mockGetDataFrame,
  getDataTable: mockGetDataTable,
}));

vi.mock("@dashframe/engine", async (importOriginal) => {
  // Import original to preserve fieldIdToColumnAlias and metricIdToColumnAlias
  // (these are pure deterministic functions; replacing them breaks assertion keys).
  const original = await importOriginal<typeof import("@dashframe/engine")>();
  return {
    ...original,
    buildInsightSQL: mockBuildInsightSQL,
  };
});

vi.mock("@dashframe/engine-browser", () => ({
  ensureTableLoaded: mockEnsureTableLoaded,
  shortenAutoGeneratedName: (name: string) => name,
}));

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const BASE_TABLE_ID = "bb000000-0000-0000-0000-000000000001" as UUID;
const BASE_DF_ID = "bb000000-0000-0000-0000-000000000002" as UUID;
const JOIN_TABLE_ID = "jj000000-0000-0000-0000-000000000001" as UUID;
const JOIN_DF_ID = "jj000000-0000-0000-0000-000000000002" as UUID;

// Base table: orders with an order_id and a fk dept_id
const BASE_FK_FIELD: Field = {
  id: "bb111111-aaaa-aaaa-aaaa-111111111111" as UUID,
  name: "dept_id",
  tableId: BASE_TABLE_ID,
  columnName: "dept_id",
  type: "string",
};
const BASE_ORDER_FIELD: Field = {
  id: "bb222222-bbbb-bbbb-bbbb-222222222222" as UUID,
  name: "order_id",
  tableId: BASE_TABLE_ID,
  columnName: "order_id",
  type: "string",
};

// Join table: departments with dept_id (join key) and dept_name
const RIGHT_JOIN_KEY_FIELD: Field = {
  id: "jj333333-cccc-cccc-cccc-333333333333" as UUID,
  name: "dept_id",
  tableId: JOIN_TABLE_ID,
  columnName: "dept_id",
  type: "string",
};
const JOIN_OTHER_FIELD: Field = {
  id: "jj444444-dddd-dddd-dddd-444444444444" as UUID,
  name: "dept_name",
  tableId: JOIN_TABLE_ID,
  columnName: "dept_name",
  type: "string",
};

const baseTable: DataTable = {
  id: BASE_TABLE_ID,
  name: "orders",
  dataSourceId: "33333333-3333-3333-3333-333333333333" as UUID,
  table: "orders.csv",
  fields: [BASE_FK_FIELD, BASE_ORDER_FIELD],
  metrics: [],
  dataFrameId: BASE_DF_ID,
  createdAt: 0,
};

const joinTable: DataTable = {
  id: JOIN_TABLE_ID,
  name: "departments",
  dataSourceId: "33333333-3333-3333-3333-333333333333" as UUID,
  table: "departments.csv",
  fields: [RIGHT_JOIN_KEY_FIELD, JOIN_OTHER_FIELD],
  metrics: [],
  dataFrameId: JOIN_DF_ID,
  createdAt: 0,
};

const insight: Insight = {
  id: "insight0-0000-0000-0000-000000000001" as UUID,
  name: "Orders with departments",
  baseTableId: BASE_TABLE_ID,
  selectedFields: [BASE_ORDER_FIELD.id, BASE_FK_FIELD.id],
  metrics: [],
  joins: [
    {
      type: "inner",
      rightTableId: JOIN_TABLE_ID,
      leftKey: "dept_id",
      rightKey: "dept_id",
    },
  ],
  createdAt: 0,
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("useInsightPagination — allFields excludes dropped right join-keys", () => {
  beforeEach(() => {
    vi.clearAllMocks();

    mockUseDuckDB.mockReturnValue({
      connection: mockConnection,
      isInitialized: true,
      isLoading: false,
    });

    // getDataTable: first call returns baseTable, second returns joinTable
    mockGetDataTable
      .mockResolvedValueOnce(baseTable)
      .mockResolvedValueOnce(joinTable);

    // buildInsightSQL returns a minimal SQL to allow count + preview queries
    mockBuildInsightSQL.mockReturnValue("SELECT 1");

    // Count query returns 0 rows
    mockQuery.mockResolvedValueOnce({ toArray: () => [{ count: 0 }] });
    // Preview query returns no rows (no columns to extract — that's fine for this test)
    mockQuery.mockResolvedValueOnce({ toArray: () => [] });

    mockGetDataFrame.mockResolvedValue({
      id: BASE_DF_ID,
      storageType: "indexeddb",
    });

    mockEnsureTableLoaded.mockResolvedValue(undefined);
  });

  it("columnDisplayNames does NOT contain an entry for the right join-key field", async () => {
    const { result } = renderHook(() =>
      useInsightPagination({ insight, enabled: true }),
    );

    await waitFor(() => {
      expect(result.current.isReady).toBe(true);
    });

    // fieldIdToColumnAlias is preserved from the real engine module.
    // The right join-key field (RIGHT_JOIN_KEY_FIELD.id) must NOT appear in
    // columnDisplayNames — buildInsightSQL drops it from the subquery SELECT.
    const { fieldIdToColumnAlias } = await import("@dashframe/engine");
    const rightKeyAlias = fieldIdToColumnAlias(RIGHT_JOIN_KEY_FIELD.id);

    expect(result.current.columnDisplayNames).not.toHaveProperty(rightKeyAlias);
  });

  it("columnDisplayNames DOES contain entries for retained fields", async () => {
    // Mock sequence (getDataTable ×2, query ×2) is queued in beforeEach.
    const { result } = renderHook(() =>
      useInsightPagination({ insight, enabled: true }),
    );

    await waitFor(() => expect(result.current.isReady).toBe(true));

    const { fieldIdToColumnAlias } = await import("@dashframe/engine");
    const orderAlias = fieldIdToColumnAlias(BASE_ORDER_FIELD.id);
    const baseFkAlias = fieldIdToColumnAlias(BASE_FK_FIELD.id);
    const joinNameAlias = fieldIdToColumnAlias(JOIN_OTHER_FIELD.id);

    // Base table fields and non-key joined fields must be present
    expect(result.current.columnDisplayNames).toHaveProperty(orderAlias);
    expect(result.current.columnDisplayNames).toHaveProperty(baseFkAlias);
    expect(result.current.columnDisplayNames).toHaveProperty(joinNameAlias);
  });

  it("keeps BOTH sides of a bare-name collision that is NOT the join key (only step-1 drop applies)", async () => {
    // Regression for the over-drop hazard: if we ran allFields through the full
    // computeFilterableFields (step 1 + step 2), a base column and a joined
    // column sharing a bare name — neither being the join key — would BOTH be
    // dropped by step 2. But both appear in the SQL result under distinct UUID
    // aliases, so both MUST keep display/type-map entries. We apply step 1 only.
    const BASE_AUDIT: Field = {
      id: "bb555555-eeee-eeee-eeee-555555555555" as UUID,
      name: "created_at",
      tableId: BASE_TABLE_ID,
      columnName: "created_at",
      type: "date",
    };
    const JOIN_AUDIT: Field = {
      id: "jj666666-ffff-ffff-ffff-666666666666" as UUID,
      name: "created_at",
      tableId: JOIN_TABLE_ID,
      columnName: "created_at",
      type: "date",
    };
    const baseWithAudit: DataTable = {
      ...baseTable,
      fields: [BASE_FK_FIELD, BASE_ORDER_FIELD, BASE_AUDIT],
    };
    const joinWithAudit: DataTable = {
      ...joinTable,
      fields: [RIGHT_JOIN_KEY_FIELD, JOIN_OTHER_FIELD, JOIN_AUDIT],
    };

    // Override the beforeEach getDataTable sequence for this test's tables.
    mockGetDataTable.mockReset();
    mockGetDataTable
      .mockResolvedValueOnce(baseWithAudit)
      .mockResolvedValueOnce(joinWithAudit);

    const { result } = renderHook(() =>
      useInsightPagination({ insight, enabled: true }),
    );

    await waitFor(() => expect(result.current.isReady).toBe(true));

    const { fieldIdToColumnAlias } = await import("@dashframe/engine");
    const baseAuditAlias = fieldIdToColumnAlias(BASE_AUDIT.id);
    const joinAuditAlias = fieldIdToColumnAlias(JOIN_AUDIT.id);

    // Both created_at columns must keep their map entries (and their date type).
    expect(result.current.columnDisplayNames).toHaveProperty(baseAuditAlias);
    expect(result.current.columnDisplayNames).toHaveProperty(joinAuditAlias);
    expect(result.current.columnTypeMap[baseAuditAlias]).toBe("date");
    expect(result.current.columnTypeMap[joinAuditAlias]).toBe("date");
  });
});

// ---------------------------------------------------------------------------
// Empty-result column reset (YW-311)
// ---------------------------------------------------------------------------

/**
 * Contract: when a resolved result returns zero preview rows, columns and
 * fieldCount must reset to [] / 0, not retain the prior insight's values.
 *
 * This guards the YW-311 bug: `if (rows.length > 0)` skipping setColumns on
 * the zero-row path left stale schema visible.
 *
 * Generation-guard invariant (YW-303) must hold: the reset fires only inside
 * the current generation's continuation — after the gen check — so a
 * superseded in-flight init never resets the current state.
 */
describe("useInsightPagination — empty-result column reset (YW-311)", () => {
  // Minimal single-table insight; no joins needed to exercise the column path.
  const TABLE_ID = "cc000000-0000-0000-0000-000000000001" as UUID;
  const DF_ID = "cc000000-0000-0000-0000-000000000002" as UUID;

  const field: Field = {
    id: "cc111111-aaaa-aaaa-aaaa-111111111111" as UUID,
    name: "amount",
    tableId: TABLE_ID,
    columnName: "amount",
    type: "number",
  };

  const table: DataTable = {
    id: TABLE_ID,
    name: "sales",
    dataSourceId: "55555555-5555-5555-5555-555555555555" as UUID,
    table: "sales.csv",
    fields: [field],
    metrics: [],
    dataFrameId: DF_ID,
    createdAt: 0,
  };

  const insightA: Insight = {
    id: "insightA-0000-0000-0000-000000000001" as UUID,
    name: "Sales insight A",
    baseTableId: TABLE_ID,
    selectedFields: [field.id],
    metrics: [],
    createdAt: 0,
  };

  const insightB: Insight = {
    id: "insightB-0000-0000-0000-000000000002" as UUID,
    name: "Sales insight B (empty result)",
    baseTableId: TABLE_ID,
    selectedFields: [field.id],
    metrics: [],
    createdAt: 0,
  };

  beforeEach(() => {
    vi.clearAllMocks();

    mockUseDuckDB.mockReturnValue({
      connection: mockConnection,
      isInitialized: true,
      isLoading: false,
    });

    mockGetDataFrame.mockResolvedValue({ id: DF_ID, storageType: "indexeddb" });
    mockEnsureTableLoaded.mockResolvedValue(undefined);
  });

  it("resets columns and fieldCount to empty when the current generation returns zero preview rows", async () => {
    // Phase 1 — insight A: preview returns 1 row, populating columns + fieldCount.
    // Phase 2 — insight B: preview returns 0 rows → columns/fieldCount must clear.
    // Pre-fix: the `if (rows.length > 0)` guard skipped setColumns([]), leaving
    // A's columns/fieldCount visible — the YW-311 bug.

    // Phase 1 mocks: getDataTable × 1, buildInsightSQL, count query, preview query (1 row).
    mockGetDataTable.mockResolvedValue(table);
    mockBuildInsightSQL.mockReturnValue("SELECT amount FROM sales");

    mockQuery
      // A — count
      .mockResolvedValueOnce({ toArray: () => [{ count: 5 }] })
      // A — preview (1 row with column `amount`)
      .mockResolvedValueOnce({ toArray: () => [{ amount: 42 }] });

    const { result, rerender } = renderHook(
      ({ insight }: { insight: Insight }) =>
        useInsightPagination({ insight, enabled: true }),
      { initialProps: { insight: insightA } },
    );

    // Baseline: wait for A's columns to populate (non-triviality guard — ensures
    // the test would be red on pre-fix code if it reached the assertion).
    await waitFor(() => {
      expect(result.current.columns.length).toBeGreaterThan(0);
    });
    expect(result.current.fieldCount).toBe(1);

    // Phase 2 mocks: same table, but preview returns 0 rows.
    mockQuery
      // B — count
      .mockResolvedValueOnce({ toArray: () => [{ count: 0 }] })
      // B — preview (empty result)
      .mockResolvedValueOnce({ toArray: () => [] });

    // Switch to insight B.
    rerender({ insight: insightB });

    // Wait for B's totalCount to settle (observable without depending on isReady timing).
    await waitFor(() => {
      expect(result.current.totalCount).toBe(0);
    });

    // Critical assertions: stale schema from A must be gone.
    await waitFor(() => {
      expect(result.current.columns).toEqual([]);
    });
    expect(result.current.fieldCount).toBe(0);
  });
});
